<!DOCTYPE html>
<html lang="en"><head>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Amirhossein Ghadiri, PhD Student">
  <meta name="author" content="Bahman Rostami-Tabar, Supervisor">
  <title>What drives vaccine quality at the last mile?</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-5fad44d5386fec81f74364f4f05a861e.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<meta property="og:title" content="What drives vaccine quality at the last mile?">
<meta property="og:description" content="WHO EVM assessments across 77 countries | The Quality component">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="images/who.png, images/dl4sg.png, images/cardiff.png" data-background-position="12% 91%, 50% 91%, 88% 91%" data-background-repeat="no-repeat, no-repeat, no-repeat" data-background-size="auto 70px, auto 70px, auto 70px" class="quarto-title-block center">
  <h1 class="title">What drives vaccine quality at the last mile?</h1>
  <p class="subtitle">WHO EVM assessments across 77 countries | The Quality component</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Amirhossein Ghadiri, PhD Student
</div>
        <p class="quarto-title-affiliation">
            Data Lab for Social Good, Cardiff Business School, Cardiff University
          </p>
    </div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Bahman Rostami-Tabar, Supervisor
</div>
        <p class="quarto-title-affiliation">
            Data Lab for Social Good, Cardiff Business School, Cardiff University
          </p>
    </div>
</div>

</section>
<section class="slide level2">

<style>
.reveal section.tbl table { width: 100%; table-layout: fixed; border-collapse: collapse; }
.reveal section.tbl th, .reveal section.tbl td { padding: 0.12em 0.3em; vertical-align: middle; line-height: 1.15; }
.reveal section.tbl th { text-align: left; }
.reveal section.tbl td:nth-child(n+4), .reveal section.tbl th:nth-child(n+4) { text-align: right; }
.reveal section.t25 table { font-size: 0.46em; }
.reveal section.t14 table { font-size: 0.56em; }
.reveal section.t10 table { font-size: 0.6em; }
.reveal section.t7 table { font-size: 0.66em; }
.reveal section.tbl td:nth-child(3), .reveal section.tbl th:nth-child(3) { width: 36%; text-align: left; }
.reveal section.tbl td:nth-child(2), .reveal section.tbl th:nth-child(2) { width: 7%; text-align: left; }
.reveal section.tbl td:nth-child(1), .reveal section.tbl th:nth-child(1) { width: 4%; text-align: left; }
.reveal section.wide3 td:nth-child(3), .reveal section.wide3 th:nth-child(3) { width: 44%; }
.reveal section.tbl p { font-size: 0.72em; margin-top: 0.4em; }
.reveal .smallnote { font-size: 0.7em; color: #5a6b7c; }
</style>
</section>
<section id="a-fridge-in-a-small-clinic" class="slide level2">
<h2>A fridge in a small clinic</h2>
<svg viewbox="0 0 1300 400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A vaccine fridge and three opened vials, one dated, one undated, one expired" style="width:100%;max-width:1080px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"> <rect x="40" y="30" width="300" height="330" rx="14" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2.5"></rect> <line x1="40" y1="112" x2="340" y2="112" stroke="#7ba3d4" stroke-width="2.5"></line> <rect x="312" y="150" width="13" height="80" rx="6" fill="#7ba3d4"></rect> <line x1="62" y1="205" x2="300" y2="205" stroke="#7ba3d4" stroke-width="1.5"></line> <line x1="62" y1="285" x2="300" y2="285" stroke="#7ba3d4" stroke-width="1.5"></line> <g fill="#1f6db4"> <rect x="76" y="163" width="15" height="40" rx="4"></rect> <rect x="100" y="163" width="15" height="40" rx="4"></rect> <rect x="124" y="163" width="15" height="40" rx="4"></rect> <rect x="148" y="163" width="15" height="40" rx="4"></rect> <rect x="76" y="243" width="15" height="40" rx="4"></rect> <rect x="100" y="243" width="15" height="40" rx="4"></rect> <rect x="124" y="243" width="15" height="40" rx="4"></rect> </g> <line x1="380" y1="195" x2="470" y2="195" stroke="#8a97a6" stroke-width="2.5"></line> <path d="M478 195 L462 187 L462 203 Z" fill="#8a97a6"></path> <g stroke-width="2.5" fill="#ffffff"> <rect x="558" y="110" width="64" height="150" rx="10" stroke="#1f6db4"></rect> <rect x="768" y="110" width="64" height="150" rx="10" stroke="#D55E00"></rect> <rect x="978" y="110" width="64" height="150" rx="10" stroke="#D55E00"></rect> </g> <g> <rect x="561" y="192" width="58" height="62" rx="8" fill="#e3edf9"></rect> <rect x="771" y="192" width="58" height="62" rx="8" fill="#e3edf9"></rect> <rect x="981" y="192" width="58" height="62" rx="8" fill="#e3edf9"></rect> <rect x="568" y="84" width="44" height="28" rx="5" fill="#1f6db4"></rect> <rect x="778" y="84" width="44" height="28" rx="5" fill="#D55E00"></rect> <rect x="988" y="84" width="44" height="28" rx="5" fill="#D55E00"></rect> </g> <g font-size="25" text-anchor="middle"> <text x="590" y="305" fill="#1f6db4">Opened 3 Aug</text> <text x="590" y="340" fill="#33495d">day 23, still fine</text> <text x="800" y="305" fill="#D55E00">No date written</text> <text x="800" y="340" fill="#33495d">Can’t tell</text> <text x="1010" y="305" fill="#D55E00">Opened 12 Jul</text> <text x="1010" y="340" fill="#33495d">day 45, must be binned</text> </g> </g>
</svg>
<div class="fragment">
<p>Infrastructure, Equipment, IT, HR, Policies &amp; procedures, and Financial resources checks have been conducted in thousands of facilities across 77 countries, scoring each against hundreds of supply chain checks.</p>
</div>
<div class="fragment">
<p><span class="remember">Which of those checks actually go with vaccines being in good condition? That is what I set out to answer.</span></p>
<aside class="notes">
<p>About 60 seconds. Start with the picture and talk through it: the fridge on the left is what an assessor sees; on the right are three opened vials from that fridge. One was dated when it was opened and is still inside its window. One has no date at all, so nobody in that clinic can say whether it is safe. One is past the window and should already have been thrown away. Then the scale line, then read the question and pause.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="what-i-will-cover" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="remember"><strong>The question</strong></span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-assessment-three-components-and-this-is-about-quality" class="slide level2">
<h2>One assessment, three components, and this is about Quality</h2>
<p>The WHO Effective Vaccine Management assessment scores a facility against hundreds of checks, each with a code like <code>R0290</code> called requirements. It also scores a set of outcomes.</p>
<ul>
<li>Outcomes are <strong>availability</strong>, <strong>efficiency</strong>, and <strong>quality</strong>. This analysis is about <strong>quality</strong>.</li>
<li>The applied goal is a shorter instrument, an <strong>EVM-Lite</strong>. If a short checklist could check only a few things, which ones should they be?</li>
</ul>
<aside class="notes">
<p>About 45 seconds. Define requirement once, out loud, because every later slide uses the word. Then the division of labour in one breath. Land on EVM-Lite as the destination: that is what the whole talk is walking towards.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="quality-is-six-checks-three-during-a-session-three-in-the-fridge" class="slide level2">
<h2>Quality is six checks: three during a session, three in the fridge</h2>
<svg viewbox="0 0 1300 560" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="The 28 day window, and a grid of the six requirements that make up the quality score" style="width:100%;max-width:1040px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"> <rect x="120" y="70" width="740" height="46" rx="6" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect> <rect x="860" y="70" width="300" height="46" rx="6" fill="#f7e3d6" stroke="#D55E00" stroke-width="2"></rect> <line x1="120" y1="56" x2="120" y2="130" stroke="#33495d" stroke-width="2.5"></line> <line x1="860" y1="56" x2="860" y2="130" stroke="#33495d" stroke-width="2.5"></line> <g font-size="25" fill="#33495d"> <text x="120" y="42" text-anchor="middle">vial opened</text> <text x="860" y="42" text-anchor="middle">28 days later</text> <text x="490" y="101" text-anchor="middle" fill="#1f6db4">doses may still be given</text> <text x="1010" y="101" text-anchor="middle" fill="#D55E00">every dose left is waste</text> </g> <g font-size="25" fill="#33495d" text-anchor="middle"> <text x="575" y="192">When a session is observed</text> <text x="1045" y="192">When stock is inspected</text> </g> <g fill="#f4f6f8" stroke="#cfd6de" stroke-width="1.5"> <rect x="350" y="210" width="450" height="100" rx="8"></rect> <rect x="820" y="210" width="450" height="100" rx="8"></rect> <rect x="350" y="322" width="450" height="100" rx="8"></rect> <rect x="820" y="322" width="450" height="100" rx="8"></rect> </g> <g fill="#e3edf9" stroke="#7ba3d4" stroke-width="2.5"> <rect x="350" y="434" width="450" height="100" rx="8"></rect> <rect x="820" y="434" width="450" height="100" rx="8"></rect> </g> <g font-size="24" fill="#8a97a6"> <text x="374" y="244">R0710</text> <text x="374" y="276">Expired vaccines are</text> <text x="374" y="302">never administered</text> <text x="844" y="244">R0713</text> <text x="844" y="276">There are no expired</text> <text x="844" y="302">vaccines in stock</text> <text x="374" y="356">R0711</text> <text x="374" y="388">Heat damaged vaccines</text> <text x="374" y="414">are never administered</text> <text x="844" y="356">R0716</text> <text x="844" y="388">There are no heat damaged</text> <text x="844" y="414">vaccines in stock</text> </g> <g font-size="24" fill="#33495d"> <text x="374" y="468" fill="#1f6db4">R0712</text> <text x="374" y="500">No vial is used more than</text> <text x="374" y="526">28 days after opening</text> <text x="844" y="468" fill="#1f6db4">R0722</text> <text x="844" y="500">No opened vial older than</text> <text x="844" y="526">28 days is in stock</text> </g> <g font-size="25" fill="#33495d"> <text x="20" y="270">Expired</text> <text x="20" y="380">Heat damaged</text> <text x="20" y="472">Opened more than</text> <text x="20" y="502">28 days ago</text> </g> </g>
</svg>
<p>The composite score <code>QU</code> is the combination of them all.</p>
<aside class="notes">
<p>About 70 seconds, and it earns the time because everything later refers back to this grid. Take the timeline first: a vial is opened at the left mark, doses can be given for 28 days, and anything left after the right mark is waste. Then read the grid as a table. Down the left are the three ways a vaccine goes bad: it expires, it gets too hot, which the vial monitor shows by darkening past its discard point, or it sits opened for too long. Across the top is where the assessor catches it, either watching a real immunisation session or inspecting what is in the fridge. Each failure is checked both ways, which gives six requirements, and the composite QU pools all six. Say that the two in blue are the ones I follow, and that the reason the other four fade out is coming in a couple of slides. Worth flagging now that the left column can only be scored when a session is running, because that fact comes back later to explain a strange result.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-aim-here-is-to-explain-not-to-predict-or-forecast" class="slide level2">
<h2>The aim here is to explain, not to predict or forecast</h2>
<p>Following Shmueli (2010), the question here is which requirements go with quality and explain the variations in qualituy, not how to predict a facility’s score. <sup>1</sup></p>
<ul>
<li>Error metrics such as RMSE will not be reported because a small error would not tell me which requirement matters</li>
<li>Only models that hand back a <strong>readable number per requirement</strong> are allowed to give the answer</li>
</ul>
<aside class="notes">
<p>About 40 seconds. Say why the distinction bites: a model can be excellent at guessing scores and still tell you nothing you could act on. That rule disqualifies a model later that fits better than the one I use, and I want the panel to see the rule before they see the casualty.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Shmueli, G. (2010). To explain or to predict? <em>Statistical Science</em>, 25(3), 289-310.</p></li></ol></aside></section>
<section id="how-to-read-every-number-i-show" class="slide level2">
<h2>How to read every number I show</h2>
<ul>
<li><strong>R squared on unseen facilities.</strong> Facilities differ in quality. R squared is the share of that difference a fitted model accounts for, from 0 for none to 1 for all. It is always measured on facilities the model was never fitted on.</li>
<li><strong>Effect.</strong> The change in the quality score, which runs from 0 to 1, for one standard deviation more of a requirement’s score. The causal section later uses a plainer unit: the change from not met to met in full.</li>
<li><strong>Conclusive.</strong> The model is refitted on 200 random resamples of the facilities. A requirement is conclusive when the middle 95% of its effects across those refits lies on one side of zero, and at least half of the refits keep it in the model at all.</li>
<li><strong>Not applicable.</strong> Where a requirement does not apply to a facility, the linear models are given the column’s mean. The checks later remove those filled cells and look again.</li>
</ul>
<aside class="notes">
<p>About 60 seconds. This slide buys back time everywhere else, so do not rush it. The resamples idea in plain speech: shuffle which facilities you happen to look at, refit, and see whether the answer keeps pointing the same way. Say that the mean filling is new in this version of the analysis, and that a later slide removes it to check.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-1" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="remember"><strong>The data and the filters</strong></span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="from-4287-rows-down-to-one-clean-table" class="slide level2">
<h2>From 4,287 rows down to one clean table</h2>
<svg viewbox="0 0 1680 430" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Filtering funnel for facilities and requirements" style="width:100%;max-width:1230px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"> <text x="20" y="95" font-size="22" fill="#33495d">Facilities</text> <text x="20" y="285" font-size="22" fill="#33495d">Requirements</text> <g fill="#e3edf9" stroke="#7ba3d4" stroke-width="1.5"> <rect x="170" y="45" width="255" height="95" rx="6"></rect> <rect x="545" y="45" width="255" height="95" rx="6"></rect> <rect x="920" y="45" width="255" height="95" rx="6"></rect> <rect x="170" y="235" width="215" height="95" rx="6"></rect> <rect x="480" y="235" width="215" height="95" rx="6"></rect> <rect x="790" y="235" width="215" height="95" rx="6"></rect> <rect x="1100" y="235" width="180" height="95" rx="6"></rect> <rect x="1370" y="105" width="290" height="200" rx="6"></rect> </g> <g stroke="#8a97a6" stroke-width="2" fill="none"> <line x1="425" y1="92" x2="545" y2="92"></line> <line x1="800" y1="92" x2="920" y2="92"></line> <line x1="385" y1="282" x2="480" y2="282"></line> <line x1="695" y1="282" x2="790" y2="282"></line> <line x1="1005" y1="282" x2="1100" y2="282"></line> <line x1="1175" y1="120" x2="1370" y2="160"></line> <line x1="1280" y1="282" x2="1370" y2="250"></line> </g> <g fill="#8a97a6"> <path d="M545 92 L533 86 L533 98 Z"></path> <path d="M920 92 L908 86 L908 98 Z"></path> <path d="M480 282 L468 276 L468 288 Z"></path> <path d="M790 282 L778 276 L778 288 Z"></path> <path d="M1100 282 L1088 276 L1088 288 Z"></path> <path d="M1370 160 L1356 158 L1360 169 Z"></path> <path d="M1370 250 L1358 244 L1360 256 Z"></path> </g> <g font-size="23" fill="#1f6db4" text-anchor="middle"> <text x="297" y="83">4,287</text> <text x="297" y="113">assessment rows</text> <text x="672" y="83">2,290</text> <text x="672" y="113">Service Points</text> <text x="1047" y="83">2,258</text> <text x="1047" y="113">scored on quality</text> <text x="277" y="273">891</text> <text x="277" y="303">requirements</text> <text x="587" y="273">207</text> <text x="587" y="303">inputs only</text> <text x="897" y="273">171</text> <text x="897" y="303">widely applicable</text> <text x="1190" y="273">170</text> <text x="1190" y="303">unique</text> <text x="1515" y="175">2,258 facilities</text> <text x="1515" y="210">172 columns</text> <text x="1515" y="245">77 countries</text> </g> <g font-size="20" fill="#33495d" text-anchor="middle"> <text x="485" y="30">keep the last mile</text> <text x="860" y="30">drop the unscored</text> <text x="432" y="372">keep the actionable</text> <text x="432" y="396">input requirements</text> <text x="742" y="372">drop if rarely</text> <text x="742" y="396">applicable</text> <text x="1052" y="372">drop 1 duplicate</text> </g> </g>
</svg>
<aside class="notes">
<p>No input requirement shares a questionnaire item with the quality scores, so nothing on the left hand-side restates the answer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside class="notes">
<p>About 75 seconds, the longest single slide, so guide it properly. Top row, left to right: 4,287 rows cover every level of the supply chain; I keep the 2,290 Service Points because that is the last mile, the fridge in the story; 2,258 of those have a quality score. Bottom row: 891 requirements in the workbook; 207 are the input requirements a manager can actually act on; 36 go because they apply to fewer than one facility in ten; one is an exact duplicate of another. The two rows meet on the right: 2,258 facilities, 172 columns, which is the 170 requirements plus assessment year and target population, across 77 countries. Then the line underneath: I checked that no requirement is scored from the same questionnaire item as the outcome, which would have made the whole thing circular.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-year-column-is-really-a-country-label" class="slide level2">
<h2>The year column is really a country label</h2>
<p>Every one of the 77 countries was assessed in exactly one year. Not one country appears in two different years.</p>
<ul>
<li>So the year tells which group of countries a facility belongs to, and nothing about change over time</li>
<li>If the year looks important later, it means countries assessed in some years score better than countries assessed in others</li>
</ul>
<aside class="notes">
<ul>
<li>I keep the column, but I never read it as a trend, and this comes back twice</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<aside class="notes">
<p>About 35 seconds. Small check, large consequence. Flag now that the year turns out to matter for both components, so when it appears the panel already knows how to read it. Without this slide that result looks like a story about improvement over time, which would be wrong.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-2" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="remember"><strong>Targets and models</strong></span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="four-of-the-seven-targets-have-almost-nothing-to-explain" class="slide level2">
<h2>Four of the seven targets have almost nothing to explain</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Target</th>
<th>Facilities at full marks</th>
<th>Best R² on unseen facilities</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0712</code> vials, use within 28 days</td>
<td>54.9%</td>
<td>0.187</td>
</tr>
<tr class="even">
<td><code>R0722</code> vials, none left past 28 days</td>
<td>54.5%</td>
<td>0.171</td>
</tr>
<tr class="odd">
<td><code>QU</code> composite quality</td>
<td>58.2%</td>
<td>0.059</td>
</tr>
<tr class="even">
<td><code>R0710</code> <code>R0711</code> <code>R0713</code> <code>R0716</code></td>
<td>94 to 97%</td>
<td>0.05 or below</td>
</tr>
</tbody>
</table>
<p><strong>The composite and the two vial components are carried forward.</strong> The other four cover expired and heat-damaged vaccine, and almost every facility already passes them, so there is no variation left to explain.</p>
<aside class="notes">
<p>About 60 seconds. Read the table row by row. The near-universal pass on expired and heat-damaged stock is a finding in itself about the last mile. What still separates facilities is multi-dose vial handling. The R squared figures here come from five repeated splits of the facilities; the next slide uses twenty.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-best-fitting-model-is-not-useful" class="slide level2">
<h2>The best-fitting model is not useful</h2>
<p>Eleven model families, each run over twenty repeated splits of the facilities into 75% for fitting and 25% for testing.</p>
<ul>
<li>Random forest has the best raw test score, 0.239 on <code>R0712</code>, but it scores about 0.65 higher on the facilities it was fitted on. It memorises them.</li>
<li>XGBoost fits its training facilities perfectly, 1.000, and does worse than a straight line on new ones. Tree models cannot answer an explanatory question here.</li>
<li>Among the models that give a readable number per requirement, <strong>the elastic net wins all three targets</strong>: <span class="strong-blue">0.051</span> for <code>QU</code>, <span class="strong-blue">0.191</span> for <code>R0712</code>, <span class="strong-blue">0.180</span> for <code>R0722</code>.</li>
</ul>
<aside class="notes">
<p>About 65 seconds. This is the rule from the earlier slide biting. Random forest wins on paper and still loses, and I want that said plainly. The elastic net is worth one sentence: it keeps a small number of requirements and pushes the rest to exactly zero, so what comes out is already a short list.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="knowing-the-country-helps-a-lot-which-is-why-it-is-kept-out-of-the-predictors" class="slide level2">
<h2>Knowing the country helps a lot, which is why it is kept out of the predictors</h2>
<svg viewbox="0 0 1300 445" xmlns="http://www.w3.org/2000/svg" role="img" style="width:100%;max-width:1080px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><line x1="150" y1="345" x2="1240" y2="345" stroke="#8a97a6" stroke-width="2"></line><text x="60" y="200" font-size="21" fill="#33495d" transform="rotate(-90 60 200)" text-anchor="middle">R² unseen</text><rect x="240" y="304" width="80" height="41" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="280" y="294" font-size="22" fill="#33495d" text-anchor="middle">0.051</text><rect x="330" y="254" width="80" height="91" fill="#1f6db4"></rect><text x="370" y="244" font-size="22" fill="#33495d" text-anchor="middle">0.114</text><rect x="600" y="192" width="80" height="153" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="640" y="182" font-size="22" fill="#33495d" text-anchor="middle">0.191</text><rect x="690" y="86" width="80" height="259" fill="#1f6db4"></rect><text x="730" y="76" font-size="22" fill="#33495d" text-anchor="middle">0.324</text><rect x="960" y="201" width="80" height="144" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="1000" y="191" font-size="22" fill="#33495d" text-anchor="middle">0.180</text><rect x="1050" y="99" width="80" height="246" fill="#1f6db4"></rect><text x="1090" y="89" font-size="22" fill="#33495d" text-anchor="middle">0.308</text><text x="325" y="380" font-size="26" fill="#33495d" text-anchor="middle">QU</text><text x="685" y="380" font-size="26" fill="#33495d" text-anchor="middle">R0712</text><text x="1045" y="380" font-size="26" fill="#33495d" text-anchor="middle">R0722</text><rect x="230" y="405" width="26" height="18" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="266" y="420" font-size="22" fill="#33495d">requirements only</text><rect x="650" y="405" width="26" height="18" fill="#1f6db4"></rect><text x="686" y="420" font-size="22" fill="#33495d">plus one column per country</text></g>
</svg>
<aside class="notes">
<p>About 55 seconds. Walk the chart: pale bars are the model I report, solid bars add one column per country, and every pair roughly doubles. Between a fifth and two fifths of all variation sits between countries: 21% for the composite, 41% and 41% for the components. That is income and infrastructure, and no facility can act on it. Once country is in the model every requirement number becomes a within-country comparison, which hides how small the requirement signal really is. So I pay the price of the pale bars on purpose, and the next slide measures that price.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-3" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="remember"><strong>What drives quality</strong></span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-requirements-drive-the-composite-score-and-one-of-them-pulls-it-down" class="slide level2 tight-table">
<h2>Two requirements drive the composite score, and one of them pulls it down</h2>
<style>
section.tight-table table { width: 100%; table-layout: fixed; font-size: 0.8em; }
section.tight-table th, section.tight-table td { padding: 0.3em 0; vertical-align: middle; }
section.tight-table th:nth-child(1), section.tight-table td:nth-child(1) { width: 12%; }
section.tight-table th:nth-child(2), section.tight-table td:nth-child(2) { width: 72%; padding-left: 0; }
section.tight-table th:nth-child(3), section.tight-table td:nth-child(3) { width: 16%; text-align: right !important; padding-right: 0; }
</style>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What is checked</th>
<th>Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0290</code></td>
<td>Responsible staff know the discard time of multi-dose vials.</td>
<td><span class="strong-blue">+0.0102</span></td>
</tr>
<tr class="even">
<td><code>R0040</code></td>
<td>The facility has sufficient positive cold storage capacity for the expected maximum stock of vaccines.</td>
<td><span class="orange">-0.0114</span></td>
</tr>
<tr class="odd">
<td><code>R0322</code></td>
<td>The facility has SOPs for the multi-dose vial policy. Borderline: its interval touches zero.</td>
<td><span class="strong-blue">+0.0061</span></td>
</tr>
<tr class="even">
<td><code>R0156</code></td>
<td>The temperature record is a graph rather than a list. Borderline, the same way.</td>
<td><span class="orange">-0.0061</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><span class="remember">Meeting a WHO requirement can go with a worse quality score. Section 5 explains why.</span></p>
<aside class="notes">
<p>About 70 seconds. Two are conclusive, two sit just outside: their 200-resample intervals touch zero but stop there, and both are kept in over 90% of refits. The blue one is exactly what the assessment intends, and it is about the vials from the opening story. Then slow right down on the orange one: more fridge space goes with worse quality. Do not explain it yet. Reveal the last line, let it sit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="on-the-two-quality-components" class="slide level2 no-footer two-comp">
<h2>On the two Quality components</h2>
<style>
body:has(section.no-footer.present) div.footer { display: none !important; }
section.two-comp div.columns { font-size: 0.82em; }
section.two-comp div.column { box-sizing: border-box; padding: 0; }
section.two-comp .columns > .column > :not(ul, ol) { margin-left: 0; margin-right: 0.35rem; }
section.two-comp .columns > .column:last-child > :not(ul, ol) { margin-left: 0.35rem; margin-right: 0; }
section.two-comp ul { margin-top: 0.15em; padding-left: 0.9em; }
section.two-comp li { margin-bottom: 0.35em; line-height: 1.25; }
section.two-comp .defn { display: block; color: #5a6b7c; margin: 0.15em 0 0.55em 0; }
section.two-comp > p { font-size: 0.82em; }
</style>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong><code>R0712</code>, four conclusive</strong></p>
<p><span class="defn">Multi-dose vial vaccines are never administered more than 28 days after opening.</span></p>
<ul>
<li><code>R0290</code> Staff know the discard time of multi-dose vials. <span class="strong-blue">+0.0403</span></li>
<li><code>R0257</code> Staff are trained how to monitor supply chain performance. <span class="strong-blue">+0.0387</span></li>
<li><code>R0037</code> Storage buildings have functional certified fire extinguishers. <span class="strong-blue">+0.0289</span></li>
<li><code>R0272</code> Staff know the key principles of vaccine and dry goods storage. <span class="strong-blue">+0.0263</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong><code>R0722</code>, five conclusive</strong></p>
<p><span class="defn">There are no opened multi-dose vials in stock that were opened more than 28 days ago.</span></p>
<ul>
<li><code>R0037</code> Storage buildings have functional certified fire extinguishers. <span class="strong-blue">+0.0463</span></li>
<li><code>R0293</code> Staff know the main types of opened vial wastage. <span class="strong-blue">+0.0385</span></li>
<li><code>R0290</code> Staff know the discard time of multi-dose vials. <span class="strong-blue">+0.0363</span></li>
<li><code>R0358</code> Staff are paid in full and on time. <span class="strong-blue">+0.0333</span></li>
<li><code>R0129</code> Waste is stored in plastic or metal bins. <span class="strong-blue">+0.0297</span></li>
</ul>
</div></div>
<p><span class="remember"><code>R0290</code>, knowing when a vial must go, is the only requirement on all three lists.</span></p>
<div class="footer">
<p>&nbsp;</p>
</div>
<aside class="notes">
<p>About 70 seconds. Read both columns aloud, then land the common thread. Point out the odd ones honestly: fire extinguishers, salaries and waste bins cannot touch a vial, so something else is behind them, and sections 5 and 6 deal with it. The assessment year is conclusive for both components too, which is the country label from earlier showing through rather than any change over time.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-the-composite-score-1-to-13" class="slide level2 tbl t25">
<h2>The 25 largest effects on the composite score, 1 to 13</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>90%</td>
<td>90%</td>
<td>-0.0114</td>
<td>-0.0167 to -0.0062</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>90%</td>
<td>90%</td>
<td>+0.0102</td>
<td>+0.0028 to +0.0171</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0322</code></td>
<td>SOPs for the multi-dose vial policy</td>
<td>89%</td>
<td>65%</td>
<td>+0.0061</td>
<td>+0.0000 to +0.0128</td>
<td>94%</td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>96%</td>
<td>41%</td>
<td>-0.0061</td>
<td>-0.0119 to +0.0000</td>
<td>96%</td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>100%</td>
<td>54%</td>
<td>+0.0057</td>
<td>+0.0000 to +0.0125</td>
<td>94%</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0130</code></td>
<td>Bins are colour coded for different types of waste</td>
<td>70%</td>
<td>56%</td>
<td>+0.0054</td>
<td>+0.0000 to +0.0118</td>
<td>93%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>97%</td>
<td>33%</td>
<td>+0.0050</td>
<td>+0.0000 to +0.0116</td>
<td>92%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>50%</td>
<td>52%</td>
<td>+0.0046</td>
<td>+0.0000 to +0.0097</td>
<td>93%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>100%</td>
<td>19%</td>
<td>+0.0045</td>
<td>+0.0000 to +0.0110</td>
<td>91%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0136</code></td>
<td>Supply chain staff have work mobile phones</td>
<td>100%</td>
<td>59%</td>
<td>+0.0044</td>
<td>+0.0000 to +0.0129</td>
<td>83%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>98%</td>
<td>24%</td>
<td>+0.0042</td>
<td>+0.0000 to +0.0123</td>
<td>82%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0292</code></td>
<td>Staff know how to calculate the unopened vial wastage rate</td>
<td>100%</td>
<td>51%</td>
<td>+0.0035</td>
<td>+0.0000 to +0.0096</td>
<td>85%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0275</code></td>
<td>Staff know how to use the stock management system</td>
<td>100%</td>
<td>73%</td>
<td>+0.0034</td>
<td>+0.0000 to +0.0090</td>
<td>78%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Applies to: share of facilities where the requirement was asked. At max: share of those facilities meeting it in full. Kept in: share of the 200 resamples that kept the requirement. Effect is per standard deviation of the requirement’s score, on the 0 to 1 target.</span></p>
<aside class="notes">
<p>About 60 seconds. Read the conclusive rows and then say what the rest of the table is for: a ranking by size so the reader can see how quickly the evidence runs out, not a list of findings. Point at the two profile columns: a requirement almost everyone meets has little room to show an effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-the-composite-score-14-to-25" class="slide level2 tbl t25">
<h2>The 25 largest effects on the composite score, 14 to 25</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>14</td>
<td><code>R0122</code></td>
<td>Waste handlers have boots</td>
<td>16%</td>
<td>60%</td>
<td>+0.0030</td>
<td>+0.0000 to +0.0105</td>
<td>74%</td>
<td></td>
</tr>
<tr class="even">
<td>15</td>
<td><code>R0064</code></td>
<td>Vaccine refrigerator/freezers have door open alarms</td>
<td>35%</td>
<td>10%</td>
<td>-0.0030</td>
<td>-0.0120 to +0.0000</td>
<td>68%</td>
<td></td>
</tr>
<tr class="odd">
<td>16</td>
<td><code>R0269</code></td>
<td>Staff can correctly read a 30DTR</td>
<td>71%</td>
<td>85%</td>
<td>+0.0027</td>
<td>+0.0000 to +0.0100</td>
<td>70%</td>
<td></td>
</tr>
<tr class="even">
<td>17</td>
<td><code>R0186</code></td>
<td>Stock record form has a field for VVM status</td>
<td>95%</td>
<td>60%</td>
<td>-0.0025</td>
<td>-0.0085 to +0.0000</td>
<td>62%</td>
<td></td>
</tr>
<tr class="odd">
<td>18</td>
<td><code>R0298</code></td>
<td>Staff know how to dispose of expired temperature monitoring devices</td>
<td>100%</td>
<td>82%</td>
<td>-0.0022</td>
<td>-0.0075 to +0.0000</td>
<td>72%</td>
<td></td>
</tr>
<tr class="even">
<td>19</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>99%</td>
<td>87%</td>
<td>+0.0019</td>
<td>+0.0000 to +0.0083</td>
<td>60%</td>
<td></td>
</tr>
<tr class="odd">
<td>20</td>
<td><code>R0212</code></td>
<td>Receipt form has a field for Freeze indicator status of vaccines received</td>
<td>84%</td>
<td>56%</td>
<td>-0.0018</td>
<td>-0.0078 to +0.0000</td>
<td>58%</td>
<td></td>
</tr>
<tr class="even">
<td>21</td>
<td><code>R0154</code></td>
<td>The form has fields for entering AM and PM temperatures</td>
<td>96%</td>
<td>84%</td>
<td>+0.0018</td>
<td>+0.0000 to +0.0088</td>
<td>50%</td>
<td></td>
</tr>
<tr class="odd">
<td>22</td>
<td><code>R0210</code></td>
<td>Receipt form has a field for Quantity of vaccines received</td>
<td>100%</td>
<td>78%</td>
<td>-0.0017</td>
<td>-0.0067 to +0.0000</td>
<td>57%</td>
<td></td>
</tr>
<tr class="even">
<td>23</td>
<td><code>R0326</code></td>
<td>SOPs for disposal of sharps waste</td>
<td>56%</td>
<td>63%</td>
<td>+0.0016</td>
<td>+0.0000 to +0.0063</td>
<td>53%</td>
<td></td>
</tr>
<tr class="odd">
<td>24</td>
<td><code>R0073</code></td>
<td>Sufficient coolant pack storage capacity for daily demand</td>
<td>96%</td>
<td>37%</td>
<td>-0.0016</td>
<td>-0.0071 to +0.0000</td>
<td>60%</td>
<td></td>
</tr>
<tr class="even">
<td>25</td>
<td><code>R0077</code></td>
<td>Transport is always available for scheduled vaccine distribution, collect…</td>
<td>37%</td>
<td>95%</td>
<td>+0.0015</td>
<td>+0.0000 to +0.0103</td>
<td>40%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked by the size of the average effect. Below the conclusive rows the intervals include zero, so the order says where the evidence thins out, not which of these matter.</span></p>
<aside class="notes">
<p>About 30 seconds. Do not read these rows. Say that from here down the intervals include zero, and move on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-r0712-1-to-13" class="slide level2 tbl t25">
<h2>The 25 largest effects on <code>R0712</code>, 1 to 13</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>100%</td>
<td>92%</td>
<td>+0.0403</td>
<td>+0.0137 to +0.0620</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>100%</td>
<td>56%</td>
<td>+0.0387</td>
<td>+0.0094 to +0.0691</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>100%</td>
<td>23%</td>
<td>+0.0289</td>
<td>+0.0007 to +0.0508</td>
<td>98%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>99%</td>
<td>88%</td>
<td>+0.0263</td>
<td>+0.0017 to +0.0546</td>
<td>98%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>97%</td>
<td>44%</td>
<td>-0.0227</td>
<td>-0.0515 to +0.0000</td>
<td>94%</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0270</code></td>
<td>Staff know the correct storage temperature for each vaccine</td>
<td>99%</td>
<td>41%</td>
<td>+0.0194</td>
<td>+0.0000 to +0.0529</td>
<td>83%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0130</code></td>
<td>Bins are colour coded for different types of waste</td>
<td>72%</td>
<td>56%</td>
<td>+0.0187</td>
<td>+0.0000 to +0.0431</td>
<td>92%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>100%</td>
<td>29%</td>
<td>+0.0185</td>
<td>+0.0000 to +0.0519</td>
<td>83%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0002</code></td>
<td>A functional landline telephone</td>
<td>100%</td>
<td>18%</td>
<td>+0.0178</td>
<td>+0.0000 to +0.0454</td>
<td>90%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>52%</td>
<td>49%</td>
<td>+0.0175</td>
<td>+0.0000 to +0.0426</td>
<td>88%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0129</code></td>
<td>Waste is stored in plastic or metal bins</td>
<td>100%</td>
<td>48%</td>
<td>+0.0156</td>
<td>+0.0000 to +0.0442</td>
<td>86%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>98%</td>
<td>33%</td>
<td>+0.0138</td>
<td>+0.0000 to +0.0371</td>
<td>84%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0305</code></td>
<td>SOPs for vaccine temperature monitoring in storage</td>
<td>99%</td>
<td>30%</td>
<td>+0.0115</td>
<td>+0.0000 to +0.0459</td>
<td>60%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Applies to: share of facilities where the requirement was asked. At max: share of those facilities meeting it in full. Kept in: share of the 200 resamples that kept the requirement. Effect is per standard deviation of the requirement’s score, on the 0 to 1 target.</span></p>
<aside class="notes">
<p>About 60 seconds. Read the conclusive rows and then say what the rest of the table is for: a ranking by size so the reader can see how quickly the evidence runs out, not a list of findings. Point at the two profile columns: a requirement almost everyone meets has little room to show an effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-r0712-14-to-25" class="slide level2 tbl t25">
<h2>The 25 largest effects on <code>R0712</code>, 14 to 25</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>14</td>
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>100%</td>
<td>79%</td>
<td>+0.0104</td>
<td>+0.0000 to +0.0397</td>
<td>70%</td>
<td></td>
</tr>
<tr class="even">
<td>15</td>
<td><code>R0311</code></td>
<td>SOPs for managing vaccine stock transactions</td>
<td>99%</td>
<td>69%</td>
<td>+0.0097</td>
<td>+0.0000 to +0.0402</td>
<td>52%</td>
<td></td>
</tr>
<tr class="odd">
<td>16</td>
<td><code>R0327</code></td>
<td>SOPs for management of used vials</td>
<td>100%</td>
<td>67%</td>
<td>+0.0069</td>
<td>+0.0000 to +0.0355</td>
<td>39%</td>
<td></td>
</tr>
<tr class="even">
<td>17</td>
<td><code>R0233</code></td>
<td>At least one member of staff is responsible for annual work planning</td>
<td>100%</td>
<td>62%</td>
<td>+0.0068</td>
<td>+0.0000 to +0.0256</td>
<td>55%</td>
<td></td>
</tr>
<tr class="odd">
<td>18</td>
<td><code>R0182</code></td>
<td>Stock record form has a field for Presentation (# doses per vial)</td>
<td>100%</td>
<td>71%</td>
<td>+0.0067</td>
<td>+0.0000 to +0.0286</td>
<td>53%</td>
<td></td>
</tr>
<tr class="even">
<td>19</td>
<td><code>R0298</code></td>
<td>Staff know how to dispose of expired temperature monitoring devices</td>
<td>100%</td>
<td>84%</td>
<td>-0.0066</td>
<td>-0.0312 to +0.0000</td>
<td>60%</td>
<td></td>
</tr>
<tr class="odd">
<td>20</td>
<td><code>R0357</code></td>
<td>Funds for staff salaries are received on time</td>
<td>19%</td>
<td>88%</td>
<td>+0.0066</td>
<td>+0.0000 to +0.0265</td>
<td>60%</td>
<td></td>
</tr>
<tr class="even">
<td>21</td>
<td><code>R0307</code></td>
<td>SOPs for vaccine storage</td>
<td>99%</td>
<td>70%</td>
<td>+0.0065</td>
<td>+0.0000 to +0.0381</td>
<td>38%</td>
<td></td>
</tr>
<tr class="odd">
<td>22</td>
<td><code>R0123</code></td>
<td>Waste handlers have an apron</td>
<td>18%</td>
<td>60%</td>
<td>+0.0063</td>
<td>+0.0000 to +0.0287</td>
<td>51%</td>
<td></td>
</tr>
<tr class="even">
<td>23</td>
<td><code>R0236</code></td>
<td>At least one member of staff is responsible for monitoring ISC performance</td>
<td>100%</td>
<td>72%</td>
<td>+0.0061</td>
<td>+0.0000 to +0.0365</td>
<td>35%</td>
<td></td>
</tr>
<tr class="odd">
<td>24</td>
<td><code>R0370</code></td>
<td>Funds received for electricity are sufficient</td>
<td>16%</td>
<td>88%</td>
<td>-0.0059</td>
<td>-0.0253 to +0.0000</td>
<td>52%</td>
<td></td>
</tr>
<tr class="even">
<td>25</td>
<td><code>R0062</code></td>
<td>Vaccine refrigerators/freezers have functioning voltage regulators</td>
<td>97%</td>
<td>41%</td>
<td>+0.0057</td>
<td>+0.0000 to +0.0272</td>
<td>54%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked by the size of the average effect. Below the conclusive rows the intervals include zero, so the order says where the evidence thins out, not which of these matter.</span></p>
<aside class="notes">
<p>About 30 seconds. Do not read these rows. Say that from here down the intervals include zero, and move on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-r0722-1-to-13" class="slide level2 tbl t25">
<h2>The 25 largest effects on <code>R0722</code>, 1 to 13</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>100%</td>
<td>21%</td>
<td>+0.0463</td>
<td>+0.0168 to +0.0737</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0293</code></td>
<td>Staff know the main types of opened-vial wastage</td>
<td>100%</td>
<td>88%</td>
<td>+0.0385</td>
<td>+0.0081 to +0.0629</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>95%</td>
<td>92%</td>
<td>+0.0363</td>
<td>+0.0112 to +0.0588</td>
<td>99%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>100%</td>
<td>81%</td>
<td>+0.0333</td>
<td>+0.0088 to +0.0589</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0129</code></td>
<td>Waste is stored in plastic or metal bins</td>
<td>100%</td>
<td>48%</td>
<td>+0.0297</td>
<td>+0.0069 to +0.0586</td>
<td>99%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>100%</td>
<td>57%</td>
<td>+0.0281</td>
<td>+0.0000 to +0.0580</td>
<td>91%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>88%</td>
<td>92%</td>
<td>-0.0173</td>
<td>-0.0427 to +0.0000</td>
<td>86%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>47%</td>
<td>50%</td>
<td>+0.0161</td>
<td>+0.0000 to +0.0423</td>
<td>88%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>99%</td>
<td>30%</td>
<td>+0.0147</td>
<td>+0.0000 to +0.0449</td>
<td>78%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0260</code></td>
<td>Staff are trained in routine refrigeration maintenance</td>
<td>100%</td>
<td>55%</td>
<td>-0.0134</td>
<td>-0.0336 to +0.0000</td>
<td>80%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0155</code></td>
<td>The form has fields for temperature alarms</td>
<td>100%</td>
<td>69%</td>
<td>-0.0113</td>
<td>-0.0359 to +0.0000</td>
<td>72%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>100%</td>
<td>91%</td>
<td>+0.0110</td>
<td>+0.0000 to +0.0336</td>
<td>76%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>98%</td>
<td>30%</td>
<td>+0.0104</td>
<td>+0.0000 to +0.0350</td>
<td>76%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Applies to: share of facilities where the requirement was asked. At max: share of those facilities meeting it in full. Kept in: share of the 200 resamples that kept the requirement. Effect is per standard deviation of the requirement’s score, on the 0 to 1 target.</span></p>
<aside class="notes">
<p>About 60 seconds. Read the conclusive rows and then say what the rest of the table is for: a ranking by size so the reader can see how quickly the evidence runs out, not a list of findings. Point at the two profile columns: a requirement almost everyone meets has little room to show an effect.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-25-largest-effects-on-r0722-14-to-25" class="slide level2 tbl t25">
<h2>The 25 largest effects on <code>R0722</code>, 14 to 25</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>14</td>
<td><code>R0326</code></td>
<td>SOPs for disposal of sharps waste</td>
<td>58%</td>
<td>69%</td>
<td>+0.0104</td>
<td>+0.0000 to +0.0355</td>
<td>71%</td>
<td></td>
</tr>
<tr class="even">
<td>15</td>
<td><code>R0236</code></td>
<td>At least one member of staff is responsible for monitoring ISC performance</td>
<td>100%</td>
<td>73%</td>
<td>+0.0104</td>
<td>+0.0000 to +0.0386</td>
<td>58%</td>
<td></td>
</tr>
<tr class="odd">
<td>16</td>
<td><code>R0062</code></td>
<td>Vaccine refrigerators/freezers have functioning voltage regulators</td>
<td>100%</td>
<td>44%</td>
<td>+0.0093</td>
<td>+0.0000 to +0.0303</td>
<td>66%</td>
<td></td>
</tr>
<tr class="even">
<td>17</td>
<td><code>R0128</code></td>
<td>The waste storage area is covered</td>
<td>100%</td>
<td>62%</td>
<td>+0.0083</td>
<td>+0.0000 to +0.0336</td>
<td>62%</td>
<td></td>
</tr>
<tr class="odd">
<td>18</td>
<td><code>R0187</code></td>
<td>Stock record form has a field for Transaction type</td>
<td>100%</td>
<td>61%</td>
<td>+0.0083</td>
<td>+0.0000 to +0.0302</td>
<td>64%</td>
<td></td>
</tr>
<tr class="even">
<td>19</td>
<td><code>R0275</code></td>
<td>Staff know how to use the stock management system</td>
<td>100%</td>
<td>75%</td>
<td>+0.0080</td>
<td>+0.0000 to +0.0328</td>
<td>64%</td>
<td></td>
</tr>
<tr class="odd">
<td>20</td>
<td><code>R0280</code></td>
<td>Staff know how to prevent freezing during transportation in cold climates</td>
<td>65%</td>
<td>24%</td>
<td>+0.0077</td>
<td>+0.0000 to +0.0311</td>
<td>60%</td>
<td></td>
</tr>
<tr class="even">
<td>21</td>
<td><code>R0323</code></td>
<td>SOPs for handling diluents</td>
<td>100%</td>
<td>68%</td>
<td>+0.0071</td>
<td>+0.0000 to +0.0327</td>
<td>46%</td>
<td></td>
</tr>
<tr class="odd">
<td>22</td>
<td><code>R0308</code></td>
<td>A vaccine storage emergency contingency plan</td>
<td>100%</td>
<td>61%</td>
<td>+0.0070</td>
<td>+0.0000 to +0.0311</td>
<td>50%</td>
<td></td>
</tr>
<tr class="even">
<td>23</td>
<td><code>R0002</code></td>
<td>A functional landline telephone</td>
<td>100%</td>
<td>17%</td>
<td>+0.0064</td>
<td>+0.0000 to +0.0290</td>
<td>57%</td>
<td></td>
</tr>
<tr class="odd">
<td>24</td>
<td><code>R0122</code></td>
<td>Waste handlers have boots</td>
<td>16%</td>
<td>65%</td>
<td>+0.0062</td>
<td>+0.0000 to +0.0256</td>
<td>52%</td>
<td></td>
</tr>
<tr class="even">
<td>25</td>
<td><code>R0106</code></td>
<td>The waste burial site has clear warning signs</td>
<td>22%</td>
<td>16%</td>
<td>+0.0058</td>
<td>+0.0000 to +0.0270</td>
<td>60%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked by the size of the average effect. Below the conclusive rows the intervals include zero, so the order says where the evidence thins out, not which of these matter.</span></p>
<aside class="notes">
<p>About 30 seconds. Do not read these rows. Say that from here down the intervals include zero, and move on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-the-ten-least-useful-requirements-were-chosen" class="slide level2">
<h2>How the ten least useful requirements were chosen</h2>
<p>The bottom of a list is harder to define than the top, because the elastic net sets many coefficients to exactly zero and nothing orders them. So the rule has three steps, applied separately to each target.</p>
<ol type="1">
<li><strong>Set aside the requirements with no room to vary</strong>: those met in full by fewer than 5% or more than 95% of the facilities where they apply. A column that never changes cannot earn a low rank.</li>
<li><strong>Among the rest, take the ten kept in the fewest of the 200 resamples.</strong> A requirement the model drops almost every time is one it has no use for.</li>
<li><strong>Break ties by the smallest average effect, then by the weakest raw correlation with the target.</strong> The correlation is only a tie-breaker; it is not what the model uses.</li>
</ol>
<aside class="notes">
<p>About 45 seconds. The WHO team asked for this as a credibility check: a method that ranks sensibly at the top should rank sensibly at the bottom too. Explain why step 1 is needed: a requirement everyone meets would otherwise land at the bottom for the wrong reason.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ten-requirements-the-model-has-least-use-for-on-the-composite-score" class="slide level2 tbl t10">
<h2>The ten requirements the model has least use for on the composite score</h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Kept in</th>
<th>Effect</th>
<th>Correlation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0321</code></td>
<td>SOPs for the shake test</td>
<td>86%</td>
<td>59%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.084</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0329</code></td>
<td>SOPs are written in a local language</td>
<td>97%</td>
<td>68%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.095</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0327</code></td>
<td>SOPs for management of used vials</td>
<td>99%</td>
<td>63%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.096</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0311</code></td>
<td>SOPs for managing vaccine stock transactions</td>
<td>99%</td>
<td>66%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.109</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0183</code></td>
<td>Stock record form has a field for Quantity</td>
<td>100%</td>
<td>83%</td>
<td>0%</td>
<td>-0.0000</td>
<td>0.041</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0386</code></td>
<td>Facility funds received for storage are sufficient</td>
<td>14%</td>
<td>89%</td>
<td>0%</td>
<td>-0.0000</td>
<td>0.013</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0185</code></td>
<td>Stock record form has a field for Expiry date</td>
<td>100%</td>
<td>78%</td>
<td>0%</td>
<td>-0.0000</td>
<td>0.021</td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0120</code></td>
<td>Waste handlers have protective eyewear</td>
<td>16%</td>
<td>51%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.078</td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0389</code></td>
<td>Funds for maintenance of buildings are received on time</td>
<td>21%</td>
<td>84%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.038</td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0393</code></td>
<td>Funds for maintenance of cold chain equipment are received on time</td>
<td>16%</td>
<td>84%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.042</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked from the bottom: 1 is the least used. Kept in: share of the 200 resamples that kept the requirement at all. Correlation: absolute raw correlation with the target, the final tie-breaker only.</span></p>
<aside class="notes">
<p>About 40 seconds. Read three or four rows, enough to show the pattern. Note that several are funding items that apply to only one facility in six, which is a theme that returns in the causal section.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ten-requirements-the-model-has-least-use-for-on-r0712" class="slide level2 tbl t10">
<h2>The ten requirements the model has least use for on <code>R0712</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Kept in</th>
<th>Effect</th>
<th>Correlation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0183</code></td>
<td>Stock record form has a field for Quantity</td>
<td>100%</td>
<td>86%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.114</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0010</code></td>
<td>Hand washing or hand sanitizing facilities</td>
<td>100%</td>
<td>90%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.117</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0316</code></td>
<td>SOPs for packing insulated containers</td>
<td>77%</td>
<td>66%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.158</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0124</code></td>
<td>Waste handlers have trousers</td>
<td>18%</td>
<td>48%</td>
<td>0%</td>
<td>-0.0000</td>
<td>0.078</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0329</code></td>
<td>SOPs are written in a local language</td>
<td>98%</td>
<td>72%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.209</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0309</code></td>
<td>SOPs/guidelines for routine maintenance of refrigeration equipment</td>
<td>97%</td>
<td>56%</td>
<td>0%</td>
<td>-0.0000</td>
<td>0.100</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0211</code></td>
<td>Receipt form has a field for VVM status of vaccines received</td>
<td>99%</td>
<td>94%</td>
<td>1%</td>
<td>-0.0000</td>
<td>0.060</td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0117</code></td>
<td>Waste handlers have protective gloves</td>
<td>35%</td>
<td>74%</td>
<td>1%</td>
<td>-0.0000</td>
<td>0.074</td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0390</code></td>
<td>Facility funds received for maintenance of buildings are sufficient</td>
<td>21%</td>
<td>84%</td>
<td>2%</td>
<td>-0.0000</td>
<td>0.043</td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0260</code></td>
<td>Staff are trained in routine refrigeration maintenance</td>
<td>97%</td>
<td>54%</td>
<td>2%</td>
<td>-0.0000</td>
<td>0.031</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked from the bottom: 1 is the least used. Kept in: share of the 200 resamples that kept the requirement at all. Correlation: absolute raw correlation with the target, the final tie-breaker only.</span></p>
<aside class="notes">
<p>About 40 seconds. Read three or four rows, enough to show the pattern. Note that several are funding items that apply to only one facility in six, which is a theme that returns in the causal section.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ten-requirements-the-model-has-least-use-for-on-r0722" class="slide level2 tbl t10">
<h2>The ten requirements the model has least use for on <code>R0722</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Applies to</th>
<th>At max</th>
<th>Kept in</th>
<th>Effect</th>
<th>Correlation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0253</code></td>
<td>Staff are trained in annual work planning</td>
<td>100%</td>
<td>47%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.055</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0185</code></td>
<td>Stock record form has a field for Expiry date</td>
<td>100%</td>
<td>82%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.089</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0329</code></td>
<td>SOPs are written in a local language</td>
<td>98%</td>
<td>72%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.171</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0307</code></td>
<td>SOPs for vaccine storage</td>
<td>100%</td>
<td>70%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.194</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0136</code></td>
<td>Supply chain staff have work mobile phones</td>
<td>100%</td>
<td>53%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.116</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0250</code></td>
<td>Two or more members of staff are assigned to manage immunization waste</td>
<td>100%</td>
<td>61%</td>
<td>0%</td>
<td>+0.0000</td>
<td>0.038</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0264</code></td>
<td>Staff are trained in planning vaccine collection/distribution and/or outr…</td>
<td>65%</td>
<td>69%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.064</td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0004</code></td>
<td>A reliable internet connection</td>
<td>100%</td>
<td>45%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.099</td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0400</code></td>
<td>Funds for vaccine transportation or outreach are received in full</td>
<td>24%</td>
<td>87%</td>
<td>1%</td>
<td>-0.0000</td>
<td>0.085</td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0210</code></td>
<td>Receipt form has a field for Quantity of vaccines received</td>
<td>100%</td>
<td>81%</td>
<td>1%</td>
<td>+0.0000</td>
<td>0.048</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Ranked from the bottom: 1 is the least used. Kept in: share of the 200 resamples that kept the requirement at all. Correlation: absolute raw correlation with the target, the final tie-breaker only.</span></p>
<aside class="notes">
<p>About 40 seconds. Read three or four rows, enough to show the pattern. Note that several are funding items that apply to only one facility in six, which is a theme that returns in the causal section.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-4" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="remember"><strong>Stress-testing the answer</strong></span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="shuffling-the-answers-finds-almost-nothing-so-the-real-counts-mean-something" class="slide level2">
<h2>Shuffling the answers finds almost nothing, so the real counts mean something</h2>
<ul>
<li>The target scores were shuffled at random across facilities and the whole machine was run again, ten times per target.</li>
<li>Real counts: <strong>2, 4 and 5</strong> conclusive requirements. On shuffled scores: one false alarm in thirty runs, on the composite, and none on the components.</li>
<li>The largest effect any shuffled run produced is a noise ceiling: 0.0063 for the composite, 0.0238 and 0.0192 for the components. Every conclusive effect clears its ceiling, and on <code>R0722</code> so does one more, training to monitor supply chain performance.</li>
</ul>
<aside class="notes">
<p>About 60 seconds. Put the first point in plain speech: if the method found requirements out of pure noise, then finding them in the real data would prove nothing. It found one in thirty tries. The noise ceiling is a second, gentler bar: anything below it could have come from noise. Everything conclusive is above it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="removing-the-filled-in-values-changes-little" class="slide level2">
<h2>Removing the filled-in values changes little</h2>
<p>Where a requirement does not apply, the model was given the column’s mean. Refitting only on facilities where the leading requirements were actually scored:</p>
<ul>
<li>All 11 leading effects keep their direction, and 8 stay conclusive.</li>
<li>The three that lose the flag are <code>R0290</code> on the composite, and <code>R0257</code> and <code>R0037</code> on <code>R0712</code>: the discard-time requirement, training, and fire extinguishers. Their effects shrink but keep their sign.</li>
<li>The composite keeps 1,810 of 2,258 facilities in this check, and the components keep 1,066 of 1,077 and 1,039 of 1,098.</li>
</ul>
<aside class="notes">
<p>About 45 seconds. This defends the one compromise in the data preparation. Be straight that the discard-time requirement on the composite halves without its filled rows; it stays positive, and it comes back strongly in the causal section.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="six-other-model-families-name-most-of-the-same-requirements" class="slide level2 tbl t14">
<h2>Six other model families name most of the same requirements</h2>
<p>Each family ranks requirements its own way, by how much shuffling a column hurts its predictions. A requirement is named when it lands in that family’s top twenty.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Composite score</th>
<th>Named by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>6 of 6</td>
</tr>
<tr class="even">
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>5 of 6</td>
</tr>
<tr class="odd">
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>5 of 6</td>
</tr>
<tr class="even">
<td><code>R0322</code></td>
<td>SOPs for the multi-dose vial policy</td>
<td>3 of 6</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><code>R0712</code></th>
<th>Named by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>6 of 6</td>
</tr>
<tr class="even">
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>3 of 6</td>
</tr>
<tr class="odd">
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>3 of 6</td>
</tr>
<tr class="even">
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>2 of 6</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><code>R0722</code></th>
<th>Named by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0293</code></td>
<td>Staff know the main types of opened-vial wastage</td>
<td>6 of 6</td>
</tr>
<tr class="even">
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>5 of 6</td>
</tr>
<tr class="odd">
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>5 of 6</td>
</tr>
<tr class="even">
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>5 of 6</td>
</tr>
<tr class="odd">
<td><code>R0129</code></td>
<td>Waste is stored in plastic or metal bins</td>
<td>4 of 6</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>About 50 seconds. The six are ridge, the fractional logit, boosted trees, bagged trees, randomised-split trees and XGBoost. The two tree families never see a filled-in value, so a requirement they name cannot be an artefact of the filling. Land on the pattern: the discard-time requirement is named by five or six families on every target; the odd ones, fire extinguishers and storage principles, get the fewest votes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-meeting-a-requirement-can-look-like-it-reduces-quality-score" class="slide level2">
<h2>Why meeting a requirement can look like it reduces Quality score</h2>
<svg viewbox="0 0 1300 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Chain showing why better equipped facilities face the harder questions" style="width:100%;max-width:1150px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"> <g fill="#e3edf9" stroke="#7ba3d4" stroke-width="1.5"> <rect x="10" y="30" width="280" height="160" rx="8"></rect> <rect x="340" y="30" width="280" height="160" rx="8"></rect> <rect x="670" y="30" width="280" height="160" rx="8"></rect> </g> <rect x="1000" y="30" width="290" height="160" rx="8" fill="#f7e3d6" stroke="#D55E00" stroke-width="2"></rect> <g stroke="#8a97a6" stroke-width="2" fill="none"> <line x1="295" y1="110" x2="335" y2="110"></line> <line x1="625" y1="110" x2="665" y2="110"></line> <line x1="955" y1="110" x2="995" y2="110"></line> </g> <g fill="#8a97a6"> <path d="M340 110 L326 103 L326 117 Z"></path> <path d="M670 110 L656 103 L656 117 Z"></path> <path d="M1000 110 L986 103 L986 117 Z"></path> </g> <g font-size="20" fill="#33495d" text-anchor="middle"> <text x="150" y="68">Three of the six quality</text> <text x="150" y="100">checks are only scored</text> <text x="150" y="132">while an assessor</text> <text x="150" y="164">watches a real session</text> <text x="480" y="68">They are the hard ones.</text> <text x="480" y="100">Only a facility with</text> <text x="480" y="132">vaccines in use gets</text> <text x="480" y="164">asked them</text> <text x="810" y="68">Better equipped</text> <text x="810" y="100">facilities are busier,</text> <text x="810" y="132">so they get asked</text> <text x="810" y="164">more often</text> <text x="1145" y="68">So their score can</text> <text x="1145" y="100">come out lower, even</text> <text x="1145" y="132">though their vaccines</text> <text x="1145" y="164">are no worse</text> </g> </g>
</svg>
<p>Take <code>R0040</code>, having enough cold storage. <strong>90%</strong> of facilities meet it. Those that do are asked the multi-dose vial questions <strong>11 points more often</strong>, and they average <strong>0.890</strong> against <strong>0.938</strong> for those that do not.</p>
<aside class="notes">
<p>About 45 seconds, and it is the idea the whole section turns on, so do not rush. Walk the four boxes left to right. Box one points back to the grid: the three checks that need a session in progress. Box two: those are the questions facilities actually fail, and you can only fail a question you were asked. Box three: a facility with spare fridge capacity is a facility running sessions. Box four: so the better equipped facility sits the harder test and can score lower for a reason that has nothing to do with its vaccines. Then read the cold storage numbers as the worked example.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-same-pressure-pulls-every-requirement-down-so-a-positive-gap-is-earned-against-a-headwind" class="slide level2 tbl t10 wide3">
<h2>The same pressure pulls every requirement down, so a positive gap is earned against a headwind</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Requirement</th>
<th>Met by</th>
<th>Score if met</th>
<th>Score if not</th>
<th>Gap</th>
<th>Asked the session questions more often, by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>90%</td>
<td>0.888</td>
<td>0.811</td>
<td>+0.076</td>
<td>+11 points</td>
</tr>
<tr class="even">
<td><code>R0130</code></td>
<td>Bins are colour coded for different types of waste</td>
<td>57%</td>
<td>0.909</td>
<td>0.870</td>
<td>+0.039</td>
<td>+4 points</td>
</tr>
<tr class="odd">
<td><code>R0270</code></td>
<td>Staff know the correct storage temperature for each vaccine</td>
<td>37%</td>
<td>0.884</td>
<td>0.890</td>
<td>-0.005</td>
<td>+14 points</td>
</tr>
<tr class="even">
<td><code>R0005</code></td>
<td>At least eight hours of grid electricity each day</td>
<td>94%</td>
<td>0.900</td>
<td>0.925</td>
<td>-0.025</td>
<td>+1 points</td>
</tr>
<tr class="odd">
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>41%</td>
<td>0.871</td>
<td>0.897</td>
<td>-0.026</td>
<td>+4 points</td>
</tr>
<tr class="even">
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>90%</td>
<td>0.890</td>
<td>0.938</td>
<td>-0.048</td>
<td>+11 points</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">The six requirements the model families agree on most. Every one is asked the session-based questions more often when met; only two still score higher when met.</span></p>
<aside class="notes">
<p>About 45 seconds. Read the gap column and the exposure column together. Every requirement is exposed to the harder questions more often when met, so every gap is pulled towards the negative. The two that still land positive, the discard time and colour-coded bins, are managing it against that headwind. The four negatives are what the artefact predicts, and cold storage is the clearest. Close on the rule: a statistical signal is not enough, there must also be a route from the requirement to the vial.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-short-list-keeps-most-of-the-signal-and-the-top-25-beats-all-172" class="slide level2">
<h2>A short list keeps most of the signal, and the top 25 beats all 172</h2>
<svg viewbox="0 0 1300 430" xmlns="http://www.w3.org/2000/svg" role="img" style="width:100%;max-width:1080px;height:auto;display:block;margin:0 auto;">
<g font-family="system-ui,-apple-system,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><line x1="150" y1="330" x2="1240" y2="330" stroke="#8a97a6" stroke-width="2"></line><text x="60" y="200" font-size="21" fill="#33495d" transform="rotate(-90 60 200)" text-anchor="middle">R² unseen</text><rect x="195" y="264" width="80" height="66" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="235" y="254" font-size="22" fill="#33495d" text-anchor="middle">0.051</text><rect x="285" y="296" width="80" height="34" fill="#1f6db4"></rect><text x="325" y="286" font-size="22" fill="#33495d" text-anchor="middle">0.026</text><rect x="375" y="227" width="80" height="103" fill="#7ba3d4"></rect><text x="415" y="217" font-size="22" fill="#33495d" text-anchor="middle">0.079</text><rect x="555" y="82" width="80" height="248" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="595" y="72" font-size="22" fill="#33495d" text-anchor="middle">0.191</text><rect x="645" y="164" width="80" height="166" fill="#1f6db4"></rect><text x="685" y="154" font-size="22" fill="#33495d" text-anchor="middle">0.128</text><rect x="735" y="50" width="80" height="280" fill="#7ba3d4"></rect><text x="775" y="40" font-size="22" fill="#33495d" text-anchor="middle">0.215</text><rect x="915" y="96" width="80" height="234" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="955" y="86" font-size="22" fill="#33495d" text-anchor="middle">0.180</text><rect x="1005" y="140" width="80" height="190" fill="#1f6db4"></rect><text x="1045" y="130" font-size="22" fill="#33495d" text-anchor="middle">0.146</text><rect x="1095" y="58" width="80" height="272" fill="#7ba3d4"></rect><text x="1135" y="48" font-size="22" fill="#33495d" text-anchor="middle">0.209</text><text x="325" y="365" font-size="26" fill="#33495d" text-anchor="middle">QU</text><text x="685" y="365" font-size="26" fill="#33495d" text-anchor="middle">R0712</text><text x="1045" y="365" font-size="26" fill="#33495d" text-anchor="middle">R0722</text><rect x="230" y="390" width="26" height="18" fill="#e3edf9" stroke="#7ba3d4" stroke-width="2"></rect><text x="266" y="405" font-size="22" fill="#33495d">all 172 columns</text><rect x="650" y="390" width="26" height="18" fill="#1f6db4"></rect><text x="686" y="405" font-size="22" fill="#33495d">conclusive only</text><rect x="1070" y="390" width="26" height="18" fill="#7ba3d4"></rect><text x="1106" y="405" font-size="22" fill="#33495d">top 25 only</text></g>
</svg>
<p><span class="smallnote">Two questions keep 51% of the composite’s fit, four keep 67% on <code>R0712</code>, five keep 81% on <code>R0722</code>. The top 25 does better than all 172 on every target because a penalised model with 147 weak columns removed can use a lighter penalty.</span></p>
<aside class="notes">
<p>About 55 seconds. Walk it: pale is everything the assessment asks, solid is the handful I named, and the middle shade is the top 25. The gap between pale and solid is what a two-question or five-question instrument would give up. Say the caveat yourself: the lists were chosen on the same facilities the refits are split from, so these are upper bounds on what a list fixed in advance would achieve.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-5" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="remember"><strong>Causal estimates</strong></span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="from-association-to-an-adjusted-effect-in-three-steps" class="slide level2">
<h2>From association to an adjusted effect, in three steps</h2>
<p>Facilities that meet one requirement tend to meet many others, so a simple comparison mixes them all together. Double machine learning compares facilities that are alike on every other column.</p>
<p>Take one requirement, say staff knowing the discard time, and call it the <strong>treatment</strong>. The quality score is the <strong>outcome</strong>. Every other column is a <strong>control</strong>.</p>
<ol type="1">
<li><strong>Remove from the outcome what the controls can predict.</strong> An elastic net predicts the outcome from the controls alone; what it cannot predict is kept. This leftover is a residual.</li>
<li><strong>Remove from the treatment what the controls can predict.</strong> A second elastic net does the same for the treatment.</li>
<li><strong>Compare the two residuals.</strong> The slope of a straight line through them is the estimate. If the two leftovers still move together, that link cannot come from any of the controls.</li>
</ol>
<p>The effect is in plain units: <strong>the change in the score when a facility goes from not meeting the requirement to meeting it in full</strong>. On the two components, 10 points means ten more facilities in a hundred meeting the target.</p>
<aside class="notes">
<p>About 90 seconds. This is the one slide that has to land. Use the discard-time example all the way through. Step 1 and 2 strip out everything the other 171 columns can explain; step 3 asks whether what is left still moves together. Then the unit: not a coefficient per standard deviation any more, but the gap between a facility whose staff know the rule and an otherwise similar facility whose staff do not.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-a-result-counts-and-why-country-is-held-fixed" class="slide level2">
<h2>How a result counts, and why country is held fixed</h2>
<ul>
<li><strong>Predictions never see the facility’s own country.</strong> Whole countries are split into five groups; each group’s residuals come from models fitted on the other four. The split is repeated five times with different groupings and the median is reported.</li>
<li><strong>q-value.</strong> About 170 columns are tested per target, so some look important by luck. A q-value is a p-value corrected for that. <strong>Conclusive means a q-value below 0.05</strong>, using standard errors that let facilities in the same country move together.</li>
<li><strong>Thin evidence.</strong> A column that applies to fewer than a quarter of facilities, or that over 95% of facilities answer the same way, is estimated but not flagged: too few facilities sit on one side of it.</li>
<li><strong>Country, two ways.</strong> Leaving country out compares facilities across all 77 countries, so differences between countries, in policies, supply systems and assessment teams, can masquerade as requirement effects. <strong>Centring every column within its country compares only facilities in the same country, which is the fairer test and the part a country programme can act on.</strong> The scan over all 172 columns uses the first to find candidates; the verdict uses the second.</li>
</ul>
<aside class="notes">
<p>About 80 seconds. Three definitions and one decision. On country: the within-country version is stricter because it throws away all between-country differences, good and bad, and asks only whether a facility that meets the requirement does better than its neighbours in the same country. That is why it is the one the conclusions rest on, and why effects shrink when it is applied.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="seven-effects-survive-adjustment-and-three-survive-every-check" class="slide level2 tbl t10">
<h2>Seven effects survive adjustment, and three survive every check</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Target</th>
<th>Code</th>
<th>What is checked</th>
<th>Effect, points</th>
<th>q</th>
<th>Kept within country</th>
<th>Hidden factor could move it by</th>
<th>Own subcategory removed</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>QU</code></td>
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>-6.2</td>
<td>0.005</td>
<td>97%</td>
<td>1%</td>
<td>-6 → -6</td>
<td>no route to a vial; the exposure effect</td>
</tr>
<tr class="even">
<td><code>R0712</code></td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>+27.4</td>
<td>0.029</td>
<td>57%</td>
<td>6%</td>
<td>+27 → +26</td>
<td>passes every check</td>
</tr>
<tr class="odd">
<td><code>R0712</code></td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>+19.6</td>
<td>0.029</td>
<td>55%</td>
<td>5%</td>
<td>+20 → +21</td>
<td>passes every check</td>
</tr>
<tr class="even">
<td><code>R0722</code></td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>+28.9</td>
<td>&lt;0.001</td>
<td>52%</td>
<td>7%</td>
<td>+29 → +33</td>
<td>passes every check</td>
</tr>
<tr class="odd">
<td><code>R0722</code></td>
<td><code>R0293</code></td>
<td>Staff know the main types of opened-vial wastage</td>
<td>+24.6</td>
<td>0.001</td>
<td>57%</td>
<td>4%</td>
<td>+25 → +27</td>
<td>passes every check</td>
</tr>
<tr class="even">
<td><code>R0722</code></td>
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>+17.8</td>
<td>0.040</td>
<td>30%</td>
<td>12%</td>
<td>+18 → +18</td>
<td>mostly between countries</td>
</tr>
<tr class="odd">
<td><code>R0722</code></td>
<td><code>R0260</code></td>
<td>Staff are trained in routine refrigeration maintenance</td>
<td>-20.4</td>
<td>0.040</td>
<td>37%</td>
<td>12%</td>
<td>-20 → -7</td>
<td>depends on the controls</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Effect: change in the score, in points out of 100, from not met to met in full. Kept within country: share of the effect that remains when every column is centred within its country. Hidden factor: the largest change a hidden factor as strong as salaries, fire extinguishers or facility size could make. Own subcategory removed: the effect when the treatment’s own subcategory is taken out of the controls.</span></p>
<aside class="notes">
<p>About 90 seconds. Read the three that pass every check first: knowing the discard time on both components, knowing the storage principles, knowing the types of opened-vial wastage. Each keeps about half its size within countries, which means half of the association came from between-country differences and half from facilities of the same country. Then the three that fail: cold storage passes every statistical check but has no route to a vial and is explained by exposure; salaries keep 30% within countries and are the effect a hidden factor could move most; the negative training effect collapses from 20 points to 7 as soon as the other training requirements leave the controls.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-requirement-that-cannot-matter-comes-out-at-nothing-within-countries" class="slide level2">
<h2>A requirement that cannot matter comes out at nothing within countries</h2>
<p>Fire extinguishers in the storage building cannot affect how long an opened vial is kept. In the screening they were conclusive on both components. They are the test of whether the adjustment removes the well-run-facility mark.</p>
<ul>
<li>After adjustment: +14 points on <code>R0712</code> with a q-value of 0.41, and +18 points on <code>R0722</code> with a q-value of 0.11. Not conclusive on either.</li>
<li>Within countries: 26% of the effect remains on <code>R0712</code>, and on <code>R0722</code> and the composite the sign flips.</li>
</ul>
<p><strong>The adjustment removes most of the mark, and holding country fixed removes the rest.</strong> That is the behaviour a working adjustment should show.</p>
<aside class="notes">
<p>About 40 seconds. This is a negative control, the same idea as a placebo. A method that still finds an effect for fire extinguishers within a country would be finding management, not fire safety. It finds nothing, which is the result that lets the knowledge effects be believed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-the-screenings-top-25-land-under-the-causal-estimate-the-composite-score" class="slide level2 tbl t25">
<h2>Where the screening’s top 25 land under the causal estimate, the composite score</h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Screening effect</th>
<th>Causal effect, points</th>
<th>q</th>
<th>Causal rank</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>-0.0114</td>
<td>-6.2</td>
<td>0.005</td>
<td>1 of 116</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>+0.0102</td>
<td>+5.6</td>
<td>0.110</td>
<td>3 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0322</code></td>
<td>SOPs for the multi-dose vial policy</td>
<td>+0.0061</td>
<td>+2.4</td>
<td>0.689</td>
<td>31 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>-0.0061</td>
<td>-3.6</td>
<td>0.333</td>
<td>15 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>+0.0057</td>
<td>+3.4</td>
<td>0.333</td>
<td>17 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0130</code></td>
<td>Bins are colour coded for different types of waste</td>
<td>+0.0054</td>
<td>+3.9</td>
<td>0.333</td>
<td>8 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>+0.0050</td>
<td>+4.4</td>
<td>0.330</td>
<td>6 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>+0.0046</td>
<td>+3.2</td>
<td>0.333</td>
<td>19 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>+0.0045</td>
<td>+3.0</td>
<td>0.382</td>
<td>22 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0136</code></td>
<td>Supply chain staff have work mobile phones</td>
<td>+0.0044</td>
<td>+5.5</td>
<td>0.330</td>
<td>4 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>+0.0042</td>
<td>+3.8</td>
<td>0.333</td>
<td>10 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0292</code></td>
<td>Staff know how to calculate the unopened vial wastage rate</td>
<td>+0.0035</td>
<td>+2.0</td>
<td>0.494</td>
<td>42 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0275</code></td>
<td>Staff know how to use the stock management system</td>
<td>+0.0034</td>
<td>+2.3</td>
<td>0.424</td>
<td>36 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>R0122</code></td>
<td>Waste handlers have boots</td>
<td>+0.0030</td>
<td>+7.7</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
<tr class="odd">
<td>15</td>
<td><code>R0064</code></td>
<td>Vaccine refrigerator/freezers have door open alarms</td>
<td>-0.0030</td>
<td>-3.1</td>
<td>0.851</td>
<td>20 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>16</td>
<td><code>R0269</code></td>
<td>Staff can correctly read a 30DTR</td>
<td>+0.0027</td>
<td>+2.4</td>
<td>0.591</td>
<td>34 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>17</td>
<td><code>R0186</code></td>
<td>Stock record form has a field for VVM status</td>
<td>-0.0025</td>
<td>-1.2</td>
<td>0.876</td>
<td>63 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>18</td>
<td><code>R0298</code></td>
<td>Staff know how to dispose of expired temperature monitoring devices</td>
<td>-0.0022</td>
<td>-2.4</td>
<td>0.333</td>
<td>32 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>19</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>+0.0019</td>
<td>+2.9</td>
<td>0.591</td>
<td>24 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>20</td>
<td><code>R0212</code></td>
<td>Receipt form has a field for Freeze indicator status of vac…</td>
<td>-0.0018</td>
<td>-1.4</td>
<td>0.868</td>
<td>54 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>21</td>
<td><code>R0154</code></td>
<td>The form has fields for entering AM and PM temperatures</td>
<td>+0.0018</td>
<td>+3.8</td>
<td>0.595</td>
<td>9 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>22</td>
<td><code>R0210</code></td>
<td>Receipt form has a field for Quantity of vaccines received</td>
<td>-0.0017</td>
<td>-2.0</td>
<td>0.689</td>
<td>43 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>23</td>
<td><code>R0326</code></td>
<td>SOPs for disposal of sharps waste</td>
<td>+0.0016</td>
<td>+0.3</td>
<td>0.987</td>
<td>97 of 116</td>
<td></td>
</tr>
<tr class="even">
<td>24</td>
<td><code>R0073</code></td>
<td>Sufficient coolant pack storage capacity for daily demand</td>
<td>-0.0016</td>
<td>-1.2</td>
<td>0.851</td>
<td>61 of 116</td>
<td></td>
</tr>
<tr class="odd">
<td>25</td>
<td><code>R0077</code></td>
<td>Transport is always available for scheduled vaccine distrib…</td>
<td>+0.0015</td>
<td>+3.7</td>
<td>0.802</td>
<td>13 of 116</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Causal rank: position among the 116 requirements with enough evidence, by the size of the adjusted effect. Thin: too few facilities on one side to rank. Conclusive: q below 0.05.</span></p>
<aside class="notes">
<p>About 45 seconds. The point of the slide is the agreement at the top and the reshuffle below it. Say where the screening’s conclusive rows land, and point at one or two that rise or fall a long way. Do not read the table.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-the-screenings-top-25-land-under-the-causal-estimate-r0712" class="slide level2 tbl t25">
<h2>Where the screening’s top 25 land under the causal estimate, <code>R0712</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Screening effect</th>
<th>Causal effect, points</th>
<th>q</th>
<th>Causal rank</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>+0.0403</td>
<td>+27.4</td>
<td>0.029</td>
<td>3 of 112</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>+0.0387</td>
<td>+22.0</td>
<td>0.070</td>
<td>6 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>+0.0289</td>
<td>+13.8</td>
<td>0.413</td>
<td>18 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>+0.0263</td>
<td>+19.6</td>
<td>0.029</td>
<td>8 of 112</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0156</code></td>
<td>The temperature record form is graphical</td>
<td>-0.0227</td>
<td>-14.8</td>
<td>0.298</td>
<td>15 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0270</code></td>
<td>Staff know the correct storage temperature for each vaccine</td>
<td>+0.0194</td>
<td>+33.3</td>
<td>0.680</td>
<td>1 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0130</code></td>
<td>Bins are colour coded for different types of waste</td>
<td>+0.0187</td>
<td>+20.1</td>
<td>0.119</td>
<td>7 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>+0.0185</td>
<td>+13.6</td>
<td>0.599</td>
<td>19 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0002</code></td>
<td>A functional landline telephone</td>
<td>+0.0178</td>
<td>+15.2</td>
<td>0.183</td>
<td>14 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>+0.0175</td>
<td>+11.3</td>
<td>0.298</td>
<td>28 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0129</code></td>
<td>Waste is stored in plastic or metal bins</td>
<td>+0.0156</td>
<td>+12.3</td>
<td>0.213</td>
<td>23 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>+0.0138</td>
<td>+16.6</td>
<td>0.310</td>
<td>9 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0305</code></td>
<td>SOPs for vaccine temperature monitoring in storage</td>
<td>+0.0115</td>
<td>+11.0</td>
<td>0.870</td>
<td>30 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>+0.0104</td>
<td>+10.2</td>
<td>0.573</td>
<td>32 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>15</td>
<td><code>R0311</code></td>
<td>SOPs for managing vaccine stock transactions</td>
<td>+0.0097</td>
<td>+12.9</td>
<td>0.754</td>
<td>21 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>16</td>
<td><code>R0327</code></td>
<td>SOPs for management of used vials</td>
<td>+0.0069</td>
<td>+8.3</td>
<td>0.795</td>
<td>39 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>17</td>
<td><code>R0233</code></td>
<td>At least one member of staff is responsible for annual work…</td>
<td>+0.0068</td>
<td>+9.0</td>
<td>0.763</td>
<td>36 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>18</td>
<td><code>R0182</code></td>
<td>Stock record form has a field for Presentation (# doses per…</td>
<td>+0.0067</td>
<td>+6.6</td>
<td>0.718</td>
<td>50 of 112</td>
<td></td>
</tr>
<tr class="odd">
<td>19</td>
<td><code>R0298</code></td>
<td>Staff know how to dispose of expired temperature monitoring devices</td>
<td>-0.0066</td>
<td>-11.7</td>
<td>0.183</td>
<td>24 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>20</td>
<td><code>R0357</code></td>
<td>Funds for staff salaries are received on time</td>
<td>+0.0066</td>
<td>+17.3</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
<tr class="odd">
<td>21</td>
<td><code>R0307</code></td>
<td>SOPs for vaccine storage</td>
<td>+0.0065</td>
<td>+7.3</td>
<td>0.798</td>
<td>43 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>22</td>
<td><code>R0123</code></td>
<td>Waste handlers have an apron</td>
<td>+0.0063</td>
<td>+12.1</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
<tr class="odd">
<td>23</td>
<td><code>R0236</code></td>
<td>At least one member of staff is responsible for monitoring…</td>
<td>+0.0061</td>
<td>+1.7</td>
<td>0.942</td>
<td>96 of 112</td>
<td></td>
</tr>
<tr class="even">
<td>24</td>
<td><code>R0370</code></td>
<td>Funds received for electricity are sufficient</td>
<td>-0.0059</td>
<td>-11.8</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
<tr class="odd">
<td>25</td>
<td><code>R0062</code></td>
<td>Vaccine refrigerators/freezers have functioning voltage reg…</td>
<td>+0.0057</td>
<td>+7.2</td>
<td>0.395</td>
<td>44 of 112</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Causal rank: position among the 112 requirements with enough evidence, by the size of the adjusted effect. Thin: too few facilities on one side to rank. Conclusive: q below 0.05.</span></p>
<aside class="notes">
<p>About 45 seconds. The point of the slide is the agreement at the top and the reshuffle below it. Say where the screening’s conclusive rows land, and point at one or two that rise or fall a long way. Do not read the table.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-the-screenings-top-25-land-under-the-causal-estimate-r0722" class="slide level2 tbl t25">
<h2>Where the screening’s top 25 land under the causal estimate, <code>R0722</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>What is checked</th>
<th>Screening effect</th>
<th>Causal effect, points</th>
<th>q</th>
<th>Causal rank</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>R0037</code></td>
<td>Storage buildings have functional fire extinguishers</td>
<td>+0.0463</td>
<td>+18.2</td>
<td>0.106</td>
<td>6 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td><code>R0293</code></td>
<td>Staff know the main types of opened-vial wastage</td>
<td>+0.0385</td>
<td>+24.6</td>
<td>0.001</td>
<td>2 of 113</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>R0290</code></td>
<td>Staff know the discard time of multi-dose vials</td>
<td>+0.0363</td>
<td>+28.9</td>
<td>&lt;0.001</td>
<td>1 of 113</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>R0358</code></td>
<td>Staff are paid in full and on time</td>
<td>+0.0333</td>
<td>+17.8</td>
<td>0.040</td>
<td>9 of 113</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>R0129</code></td>
<td>Waste is stored in plastic or metal bins</td>
<td>+0.0297</td>
<td>+14.4</td>
<td>0.085</td>
<td>20 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>R0257</code></td>
<td>Staff are trained to monitor supply chain performance</td>
<td>+0.0281</td>
<td>+17.4</td>
<td>0.179</td>
<td>12 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>R0040</code></td>
<td>Sufficient cold storage capacity for the expected maximum stock</td>
<td>-0.0173</td>
<td>-17.2</td>
<td>0.156</td>
<td>13 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>R0279</code></td>
<td>Staff know cool packs are prepared in dedicated compartments</td>
<td>+0.0161</td>
<td>+12.0</td>
<td>0.158</td>
<td>27 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>R0328</code></td>
<td>There are safe injection SOPs in the immunization room</td>
<td>+0.0147</td>
<td>+15.1</td>
<td>0.175</td>
<td>19 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>R0260</code></td>
<td>Staff are trained in routine refrigeration maintenance</td>
<td>-0.0134</td>
<td>-20.4</td>
<td>0.040</td>
<td>3 of 113</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>R0155</code></td>
<td>The form has fields for temperature alarms</td>
<td>-0.0113</td>
<td>-17.4</td>
<td>0.245</td>
<td>11 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>R0272</code></td>
<td>Staff know the principles of vaccine and dry goods storage</td>
<td>+0.0110</td>
<td>+11.6</td>
<td>0.389</td>
<td>30 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>R0251</code></td>
<td>Staff turnover is low</td>
<td>+0.0104</td>
<td>+16.7</td>
<td>0.156</td>
<td>16 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>R0326</code></td>
<td>SOPs for disposal of sharps waste</td>
<td>+0.0104</td>
<td>+11.8</td>
<td>0.753</td>
<td>29 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>15</td>
<td><code>R0236</code></td>
<td>At least one member of staff is responsible for monitoring…</td>
<td>+0.0104</td>
<td>+3.9</td>
<td>0.863</td>
<td>79 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>16</td>
<td><code>R0062</code></td>
<td>Vaccine refrigerators/freezers have functioning voltage reg…</td>
<td>+0.0093</td>
<td>+8.3</td>
<td>0.316</td>
<td>46 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>17</td>
<td><code>R0128</code></td>
<td>The waste storage area is covered</td>
<td>+0.0083</td>
<td>+8.2</td>
<td>0.413</td>
<td>47 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>18</td>
<td><code>R0187</code></td>
<td>Stock record form has a field for Transaction type</td>
<td>+0.0083</td>
<td>+11.4</td>
<td>0.320</td>
<td>32 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>19</td>
<td><code>R0275</code></td>
<td>Staff know how to use the stock management system</td>
<td>+0.0080</td>
<td>+7.6</td>
<td>0.527</td>
<td>55 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>20</td>
<td><code>R0280</code></td>
<td>Staff know how to prevent freezing during transportation in…</td>
<td>+0.0077</td>
<td>+15.9</td>
<td>0.293</td>
<td>18 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>21</td>
<td><code>R0323</code></td>
<td>SOPs for handling diluents</td>
<td>+0.0071</td>
<td>+18.3</td>
<td>0.293</td>
<td>5 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>22</td>
<td><code>R0308</code></td>
<td>A vaccine storage emergency contingency plan</td>
<td>+0.0070</td>
<td>+8.2</td>
<td>0.753</td>
<td>48 of 113</td>
<td></td>
</tr>
<tr class="odd">
<td>23</td>
<td><code>R0002</code></td>
<td>A functional landline telephone</td>
<td>+0.0064</td>
<td>+8.1</td>
<td>0.527</td>
<td>49 of 113</td>
<td></td>
</tr>
<tr class="even">
<td>24</td>
<td><code>R0122</code></td>
<td>Waste handlers have boots</td>
<td>+0.0062</td>
<td>+26.4</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
<tr class="odd">
<td>25</td>
<td><code>R0106</code></td>
<td>The waste burial site has clear warning signs</td>
<td>+0.0058</td>
<td>+24.4</td>
<td></td>
<td>thin</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Causal rank: position among the 113 requirements with enough evidence, by the size of the adjusted effect. Thin: too few facilities on one side to rank. Conclusive: q below 0.05.</span></p>
<aside class="notes">
<p>About 45 seconds. The point of the slide is the agreement at the top and the reshuffle below it. Say where the screening’s conclusive rows land, and point at one or two that rise or fall a long way. Do not read the table.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-two-rankings-agree-on-what-matters-and-disagree-below-it" class="slide level2">
<h2>The two rankings agree on what matters and disagree below it</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Composite</th>
<th><code>R0712</code></th>
<th><code>R0722</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rank correlation between the two sets of effects</td>
<td>0.51</td>
<td>0.47</td>
<td>0.54</td>
</tr>
<tr class="even">
<td>Requirements given the same sign</td>
<td>78%</td>
<td>82%</td>
<td>78%</td>
</tr>
<tr class="odd">
<td>Of the 25 largest effects, in both lists</td>
<td>14</td>
<td>13</td>
<td>13</td>
</tr>
<tr class="even">
<td>Conclusive in the screening</td>
<td>2</td>
<td>4</td>
<td>5</td>
</tr>
<tr class="odd">
<td>Conclusive after adjustment</td>
<td>1</td>
<td>2</td>
<td>4</td>
</tr>
<tr class="even">
<td>Conclusive under both</td>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
</tbody>
</table>
<p>Adjustment removed names from the conclusive lists and added one: a negative effect of refrigeration maintenance training on <code>R0722</code>, which the controls check on the earlier slide removes again. The names that dropped out are fire extinguishers on both components, training to monitor performance, waste bins, and the discard time on the composite, which stays positive but misses the threshold.</p>
<aside class="notes">
<p>About 50 seconds. Moderate agreement on the order, strong agreement on the names that matter. The requirements that drop out are the ones the mechanism reading had already set apart as marks of a well-run facility.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-6" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="remember"><strong>Subcategory scores</strong></span></li>
<li><span class="graylight">What it means and what comes next</span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fourteen-subcategory-scores-built-by-a-colleague-and-still-provisional" class="slide level2">
<h2>Fourteen subcategory scores, built by a colleague and still provisional</h2>
<p>The EVM framework groups its requirements into subcategories such as <code>C4.3 Knowledge and understanding</code> or <code>C5.3 SOPs</code>. A colleague on the project, Jayeed, built one score per subcategory and facility.</p>
<ul>
<li>Each score is constructed from the requirement-level scores inside that subcategory, allowing for requirements that do not apply to a facility and for differences in scoring between questionnaire versions, which matter most in <code>C5</code> and <code>C6</code>.</li>
<li>As a check, he rebuilt the six category scores <code>C1</code> to <code>C6</code> from them and compared the result with WHO’s own category scores.</li>
<li><strong>The adjustments for the earlier questionnaire versions have not yet been confirmed with WHO.</strong> A meeting with Paul Colrain is being arranged for that. Until then, every result in this section is provisional and may change.</li>
</ul>
<aside class="notes">
<p>About 50 seconds. Credit the construction and state the caveat in the same breath. The reason the section is here anyway: if the analysis gives the same answer at this coarser level, that is evidence the requirement-level answer is not an artefact of 170 narrow columns.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-fourteen-scores-stand-in-for-the-170-requirements" class="slide level2 tbl t14">
<h2>The fourteen scores stand in for the 170 requirements</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Code</th>
<th>Subcategory</th>
<th>Applies to</th>
<th>Mean score</th>
<th>At the maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>C1.1</code></td>
<td>Utilities &amp; services</td>
<td>100%</td>
<td>0.79</td>
<td>10%</td>
</tr>
<tr class="even">
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>100%</td>
<td>0.37</td>
<td>16%</td>
</tr>
<tr class="odd">
<td><code>C2.1.1</code></td>
<td>Cold storage equipment</td>
<td>100%</td>
<td>0.69</td>
<td>5%</td>
</tr>
<tr class="even">
<td><code>C2.2.1</code></td>
<td>Vehicles</td>
<td>37%</td>
<td>0.90</td>
<td>81%</td>
</tr>
<tr class="odd">
<td><code>C2.2.2</code></td>
<td>Insulated containers</td>
<td>90%</td>
<td>0.91</td>
<td>72%</td>
</tr>
<tr class="even">
<td><code>C2.3</code></td>
<td>Other equipment</td>
<td>100%</td>
<td>0.85</td>
<td>16%</td>
</tr>
<tr class="odd">
<td><code>C3.1</code></td>
<td>General IT equipment</td>
<td>100%</td>
<td>0.73</td>
<td>59%</td>
</tr>
<tr class="even">
<td><code>C3.2</code></td>
<td>Data management technology</td>
<td>100%</td>
<td>0.79</td>
<td>10%</td>
</tr>
<tr class="odd">
<td><code>C4.1</code></td>
<td>Staffing</td>
<td>100%</td>
<td>0.68</td>
<td>3%</td>
</tr>
<tr class="even">
<td><code>C4.2</code></td>
<td>Training</td>
<td>100%</td>
<td>0.66</td>
<td>10%</td>
</tr>
<tr class="odd">
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>100%</td>
<td>0.80</td>
<td>4%</td>
</tr>
<tr class="even">
<td><code>C5.3</code></td>
<td>SOPs</td>
<td>100%</td>
<td>0.57</td>
<td>12%</td>
</tr>
<tr class="odd">
<td><code>C6.1</code></td>
<td>Salaries</td>
<td>98%</td>
<td>0.78</td>
<td>76%</td>
</tr>
<tr class="even">
<td><code>C6.2</code></td>
<td>Funds for operations</td>
<td>33%</td>
<td>0.84</td>
<td>66%</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Each score runs from 0 to 1. Vehicles and funds for operations apply to about a third of facilities; the rest apply almost everywhere.</span></p>
<aside class="notes">
<p>About 35 seconds. Two things to point at: knowledge and understanding and staffing are smooth scores with hundreds of distinct values, while salaries takes only seven, and three quarters of facilities sit at its maximum. The same mean filling as before is used where a score does not apply.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-same-model-wins-again-and-the-fourteen-scores-explain-less-than-the-170-requirements" class="slide level2">
<h2>The same model wins again, and the fourteen scores explain less than the 170 requirements</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Composite</th>
<th><code>R0712</code></th>
<th><code>R0722</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Elastic net on 14 subcategory scores</td>
<td>0.022</td>
<td>0.169</td>
<td>0.144</td>
</tr>
<tr class="even">
<td>Elastic net on 170 requirements, from section 3</td>
<td>0.051</td>
<td>0.191</td>
<td>0.180</td>
</tr>
<tr class="odd">
<td>Random forest on 14 subcategory scores</td>
<td>0.058</td>
<td>0.223</td>
<td>0.168</td>
</tr>
</tbody>
</table>
<ul>
<li>On <code>R0712</code> the fractional logit edges the elastic net, 0.172 against 0.169, by less than the variation between splits. That counts as a tie, so <strong>the elastic net is used for all three targets</strong> and the subcategory numbers can be read against the requirement numbers.</li>
<li>Adding one column per country lifts the three to 0.130, 0.341 and 0.324. On a country never seen the figures fall to -0.063, 0.086 and 0.032.</li>
</ul>
<aside class="notes">
<p>About 55 seconds. Fourteen averages carry less information than the 170 items they summarise, so the fit drops; the ordering of the targets does not change. The tree models still memorise. Country matters even more at this level, and the unseen-country figures are the honest ones again.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="buildings-it-equipment-and-written-procedures-lift-the-composite-cold-storage-equipment-pulls-it-down" class="slide level2 tbl t14">
<h2>Buildings, IT equipment and written procedures lift the composite; cold storage equipment pulls it down</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>Subcategory</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+0.0119</td>
<td>+0.0051 to +0.0183</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>C3.1</code></td>
<td>General IT equipment</td>
<td>+0.0099</td>
<td>+0.0027 to +0.0189</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>C2.1.1</code></td>
<td>Cold storage equipment</td>
<td>-0.0085</td>
<td>-0.0144 to -0.0025</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>C5.3</code></td>
<td>SOPs</td>
<td>+0.0084</td>
<td>+0.0019 to +0.0161</td>
<td>98%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>+0.0058</td>
<td>+0.0000 to +0.0145</td>
<td>93%</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>C4.2</code></td>
<td>Training</td>
<td>+0.0036</td>
<td>+0.0000 to +0.0108</td>
<td>74%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>C2.3</code></td>
<td>Other equipment</td>
<td>+0.0023</td>
<td>+0.0000 to +0.0085</td>
<td>64%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>C2.2.1</code></td>
<td>Vehicles</td>
<td>-0.0016</td>
<td>-0.0073 to +0.0031</td>
<td>64%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>C3.2</code></td>
<td>Data management technology</td>
<td>-0.0016</td>
<td>-0.0077 to +0.0015</td>
<td>58%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>C6.1</code></td>
<td>Salaries</td>
<td>+0.0014</td>
<td>-0.0000 to +0.0072</td>
<td>54%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>C6.2</code></td>
<td>Funds for operations</td>
<td>+0.0013</td>
<td>+0.0000 to +0.0070</td>
<td>50%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>C1.1</code></td>
<td>Utilities &amp; services</td>
<td>-0.0003</td>
<td>-0.0044 to +0.0033</td>
<td>35%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>C2.2.2</code></td>
<td>Insulated containers</td>
<td>+0.0002</td>
<td>-0.0017 to +0.0041</td>
<td>30%</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>C4.1</code></td>
<td>Staffing</td>
<td>+0.0001</td>
<td>-0.0016 to +0.0022</td>
<td>18%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">All fourteen subcategories, ranked by the size of the average effect. Effect is per standard deviation of the score, on the 0 to 1 target; conclusive as before.</span></p>
<aside class="notes">
<p>About 45 seconds. Read the conclusive rows and the sign of cold storage equipment, which is negative on all three targets, the same artefact as the cold-storage requirement. Say that knowledge and understanding is conclusive on both components but just misses on the composite.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="written-procedures-knowledge-and-buildings-carry-r0712" class="slide level2 tbl t14">
<h2>Written procedures, knowledge and buildings carry <code>R0712</code></h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>Subcategory</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>C5.3</code></td>
<td>SOPs</td>
<td>+0.0626</td>
<td>+0.0294 to +0.0974</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>+0.0558</td>
<td>+0.0280 to +0.0872</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+0.0469</td>
<td>+0.0215 to +0.0700</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>C4.2</code></td>
<td>Training</td>
<td>+0.0266</td>
<td>+0.0000 to +0.0599</td>
<td>92%</td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>C6.1</code></td>
<td>Salaries</td>
<td>+0.0264</td>
<td>+0.0000 to +0.0590</td>
<td>96%</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>C2.3</code></td>
<td>Other equipment</td>
<td>+0.0066</td>
<td>+0.0000 to +0.0289</td>
<td>55%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>C3.1</code></td>
<td>General IT equipment</td>
<td>-0.0045</td>
<td>-0.0231 to +0.0000</td>
<td>38%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>C2.1.1</code></td>
<td>Cold storage equipment</td>
<td>-0.0036</td>
<td>-0.0217 to +0.0000</td>
<td>38%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>C2.2.2</code></td>
<td>Insulated containers</td>
<td>+0.0031</td>
<td>-0.0000 to +0.0199</td>
<td>36%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>C2.2.1</code></td>
<td>Vehicles</td>
<td>+0.0021</td>
<td>+0.0000 to +0.0166</td>
<td>30%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>C4.1</code></td>
<td>Staffing</td>
<td>+0.0017</td>
<td>+0.0000 to +0.0141</td>
<td>24%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>C1.1</code></td>
<td>Utilities &amp; services</td>
<td>+0.0006</td>
<td>-0.0019 to +0.0112</td>
<td>14%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>C6.2</code></td>
<td>Funds for operations</td>
<td>+0.0006</td>
<td>-0.0069 to +0.0103</td>
<td>23%</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>C3.2</code></td>
<td>Data management technology</td>
<td>-0.0002</td>
<td>-0.0072 to +0.0050</td>
<td>13%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">All fourteen subcategories, ranked by the size of the average effect. Effect is per standard deviation of the score, on the 0 to 1 target; conclusive as before.</span></p>
<aside class="notes">
<p>About 45 seconds. Read the conclusive rows and the sign of cold storage equipment, which is negative on all three targets, the same artefact as the cold-storage requirement. Say that knowledge and understanding is conclusive on both components but just misses on the composite.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="knowledge-buildings-and-salaries-carry-r0722" class="slide level2 tbl t14">
<h2>Knowledge, buildings and salaries carry <code>R0722</code></h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>Subcategory</th>
<th>Effect</th>
<th>Interval</th>
<th>Kept in</th>
<th>Concl.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>+0.0745</td>
<td>+0.0473 to +0.1020</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+0.0709</td>
<td>+0.0413 to +0.0964</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>C6.1</code></td>
<td>Salaries</td>
<td>+0.0509</td>
<td>+0.0270 to +0.0775</td>
<td>100%</td>
<td>✓</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>C5.3</code></td>
<td>SOPs</td>
<td>+0.0237</td>
<td>+0.0000 to +0.0511</td>
<td>91%</td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>C2.3</code></td>
<td>Other equipment</td>
<td>+0.0150</td>
<td>+0.0000 to +0.0426</td>
<td>80%</td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td><code>C4.2</code></td>
<td>Training</td>
<td>+0.0067</td>
<td>+0.0000 to +0.0288</td>
<td>60%</td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>C4.1</code></td>
<td>Staffing</td>
<td>+0.0043</td>
<td>+0.0000 to +0.0256</td>
<td>43%</td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td><code>C1.1</code></td>
<td>Utilities &amp; services</td>
<td>+0.0039</td>
<td>+0.0000 to +0.0229</td>
<td>41%</td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>C2.1.1</code></td>
<td>Cold storage equipment</td>
<td>-0.0026</td>
<td>-0.0168 to +0.0000</td>
<td>32%</td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td><code>C2.2.1</code></td>
<td>Vehicles</td>
<td>-0.0024</td>
<td>-0.0172 to +0.0000</td>
<td>28%</td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td><code>C6.2</code></td>
<td>Funds for operations</td>
<td>+0.0018</td>
<td>+0.0000 to +0.0159</td>
<td>27%</td>
<td></td>
</tr>
<tr class="even">
<td>12</td>
<td><code>C3.2</code></td>
<td>Data management technology</td>
<td>+0.0008</td>
<td>+0.0000 to +0.0112</td>
<td>12%</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td><code>C2.2.2</code></td>
<td>Insulated containers</td>
<td>-0.0008</td>
<td>-0.0091 to +0.0000</td>
<td>14%</td>
<td></td>
</tr>
<tr class="even">
<td>14</td>
<td><code>C3.1</code></td>
<td>General IT equipment</td>
<td>-0.0000</td>
<td>+0.0000 to +0.0000</td>
<td>3%</td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="smallnote">All fourteen subcategories, ranked by the size of the average effect. Effect is per standard deviation of the score, on the 0 to 1 target; conclusive as before.</span></p>
<aside class="notes">
<p>About 45 seconds. Read the conclusive rows and the sign of cold storage equipment, which is negative on all three targets, the same artefact as the cold-storage requirement. Say that knowledge and understanding is conclusive on both components but just misses on the composite.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-subcategory-results-pass-the-same-stress-tests" class="slide level2">
<h2>The subcategory results pass the same stress tests</h2>
<ul>
<li><strong>Shuffled scores.</strong> Thirty shuffled runs produced no conclusive subcategory at all. The noise ceilings are 0.0063, 0.0194 and 0.0160, and every conclusive effect clears its ceiling.</li>
<li><strong>Other model families.</strong> On <code>R0722</code> all three conclusive subcategories are named by all six families. On <code>R0712</code>, knowledge and written procedures are named by all six and buildings by two. On the composite the families agree least with the elastic net: they name data management (5 of 6) and knowledge (5 of 6) most often, and each of the four conclusive subcategories only twice.</li>
<li><strong>Removing filled-in values.</strong> All ten conclusive subcategory effects keep their direction and their flag; almost no facility has a filled cell at this level.</li>
<li><strong>Short lists.</strong> The conclusive subcategories alone keep 100% of the composite’s fit, 73% on <code>R0712</code> and 98% on <code>R0722</code>.</li>
</ul>
<aside class="notes">
<p>About 70 seconds. The same four checks as at requirement level. The disagreement on the composite is worth saying out loud: with only fourteen columns, the elastic net and the tree families spread their choices differently, and the composite is where every method has least to work with. The exposure check at this level finds the same thing as before: cold storage equipment is the one subcategory whose score falls when it is better.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-causal-estimate-at-subcategory-level-tells-the-same-story" class="slide level2 tbl t14">
<h2>The causal estimate at subcategory level tells the same story</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Target</th>
<th>Code</th>
<th>Subcategory</th>
<th>Effect, points</th>
<th>q</th>
<th>Conclusive</th>
<th>Conclusive in the screening</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>QU</code></td>
<td><code>C2.1.1</code></td>
<td>Cold storage equipment</td>
<td>-6</td>
<td>0.227</td>
<td></td>
<td>✓</td>
</tr>
<tr class="even">
<td><code>QU</code></td>
<td><code>C3.1</code></td>
<td>General IT equipment</td>
<td>+5</td>
<td>0.227</td>
<td></td>
<td>✓</td>
</tr>
<tr class="odd">
<td><code>QU</code></td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+5</td>
<td>0.164</td>
<td></td>
<td>✓</td>
</tr>
<tr class="even">
<td><code>R0712</code></td>
<td><code>C5.3</code></td>
<td>SOPs</td>
<td>+24</td>
<td>0.009</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td><code>R0712</code></td>
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>+51</td>
<td>0.053</td>
<td></td>
<td>✓</td>
</tr>
<tr class="even">
<td><code>R0712</code></td>
<td><code>C4.2</code></td>
<td>Training</td>
<td>+17</td>
<td>0.061</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>R0712</code></td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+18</td>
<td>0.103</td>
<td></td>
<td>✓</td>
</tr>
<tr class="even">
<td><code>R0722</code></td>
<td><code>C4.3</code></td>
<td>Knowledge &amp; understanding</td>
<td>+67</td>
<td>0.016</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="odd">
<td><code>R0722</code></td>
<td><code>C1.2</code></td>
<td>Buildings &amp; facilities</td>
<td>+26</td>
<td>0.005</td>
<td>✓</td>
<td>✓</td>
</tr>
<tr class="even">
<td><code>R0722</code></td>
<td><code>C6.1</code></td>
<td>Salaries</td>
<td>+21</td>
<td>0.005</td>
<td>✓</td>
<td>✓</td>
</tr>
</tbody>
</table>
<p><span class="smallnote">Effect: change in the target, in points out of 100, when the subcategory goes from its lowest possible score to its highest. A whole range is a large move, so a quarter of the knowledge range, 13 points on <code>R0712</code> and 17 on <code>R0722</code>, is the realistic figure to quote.</span></p>
<aside class="notes">
<p>About 60 seconds. On R0722 the three conclusive subcategories are the screening’s three. On R0712 only written procedures clears the line; knowledge has the largest effect, 51 points over its full range, but its q-value sits at 0.053, just outside. On the composite nothing is conclusive, and cold storage equipment is again the largest effect, downwards. One level up, the answer is the same: what staff know carries the two vial targets.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-i-will-cover-7" class="slide level2">
<h2>What I will cover</h2>
<ol type="1">
<li><span class="graylight">The question</span></li>
<li><span class="graylight">The data and the filters</span></li>
<li><span class="graylight">Targets and models</span></li>
<li><span class="graylight">What drives quality</span></li>
<li><span class="graylight">Stress-testing the answer</span></li>
<li><span class="graylight">Causal estimates</span></li>
<li><span class="graylight">Subcategory scores</span></li>
<li><span class="remember"><strong>What it means and what comes next</strong></span></li>
</ol>
<aside class="notes">
<p>5 seconds. Move the highlight and go.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-the-evidence-supports" class="slide level2">
<h2>What the evidence supports</h2>
<ul>
<li>Out of 170 requirements across 77 countries, quality at the last mile comes down to a handful, and <strong>what staff know is what matters</strong>: the discard time of multi-dose vials, the principles of vaccine storage, and the types of opened-vial wastage.</li>
<li>Those three pass every test in the analysis: conclusive after adjustment, about half their effect intact within countries, beyond the reach of any measured stand-in for a hidden factor, unmoved when their neighbours leave the controls, and each with a direct route to an opened vial.</li>
<li>The requirements that only mark a well-run facility, fire extinguishers, salaries, waste bins, drop out once facilities are compared within their own country.</li>
<li>The composite score is a weak target with a hard ceiling. Its one conclusive effect, cold storage capacity, is a measurement artefact: better equipped facilities sit the harder test.</li>
</ul>
<aside class="notes">
<p>About 70 seconds. Four sentences, slowly. The first is the headline. The second is why it can be believed. The third is what the causal section removed. The fourth is the honest reading of the composite.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-the-evidence-does-not-support-and-what-comes-next" class="slide level2">
<h2>What the evidence does not support, and what comes next</h2>
<ul>
<li><strong>The screening effects are associations, and the causal effects are causal only if nothing unmeasured drives both a requirement and quality.</strong> Every check narrows that doubt; none removes it.</li>
<li>Half of each knowledge effect comes from differences between countries. The within-country half is the part a facility can act on.</li>
<li>The subcategory results are provisional until the score construction is confirmed with WHO.</li>
<li>Next: confirm the subcategory scores; write the named requirements down before the next round of assessments arrives and test them on countries that played no part in choosing them; choose the controls for each requirement from the structure of the EVM framework.</li>
</ul>
<p><strong>Thank you.</strong> Questions welcome.</p>
<aside class="notes">
<p>About 45 seconds. End on the next step with the new assessments: a list fixed in advance and tested on countries that had no say in it is the one test that would settle the question.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="backup" class="title-slide slide level1 graylight center">
<h1>Backup</h1>

</section>
<section id="backup-choosing-the-model" class="slide level2">
<h2>Backup: choosing the model</h2>
<ul>
<li>Eleven families over the same twenty splits: ordinary least squares, ridge, LASSO, elastic net, fractional logit, a gamma model on the shortfall from full marks, boosted trees, bagged trees, randomised-split trees, XGBoost and the mean of the training data as a floor.</li>
<li>Plain least squares is the weakest linear model on unseen facilities for every target, so the penalties earn their place.</li>
<li>The elastic net and the LASSO tie on every target; the elastic net is reported because it handles groups of near-identical requirements more gracefully.</li>
</ul>
<aside class="notes">
<p>For questions on model choice. One line on AIC if pushed: a criterion computed inside the sample rewards exactly the hard fitting that repeated splits exist to discount.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="backup-how-the-values-that-do-not-exist-are-handled" class="slide level2">
<h2>Backup: how the values that do not exist are handled</h2>
<ul>
<li>Some requirements do not apply to a facility, and a linear model still needs a number in that cell.</li>
<li>Two options were compared: fill with the column’s mean, or fill and add a marker column saying the value was filled.</li>
<li>The markers fit slightly better and double the number of columns, and a marker coefficient is not something a manager can act on, so the simple fill is kept.</li>
<li>Two checks limit the cost: the tree families that need no filling name the same requirements, and refitting on fully scored facilities keeps every leading direction.</li>
</ul>
<aside class="notes">
<p>For questions on missing data. Be straight: markers win narrowly on fit and lose on usefulness.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="backup-quality-as-four-ordered-bands" class="slide level2">
<h2>Backup: quality as four ordered bands</h2>
<ul>
<li>The composite score was cut at 0.6, 0.8 and 0.95, and 58% of facilities land in the top band.</li>
<li>Always naming the biggest band beats the ordinal model on plain accuracy, 0.582 against 0.496, and the model’s agreement with the truth beyond chance is 0.092, weak by any usual standard.</li>
<li>The top twenty requirements change under banding while no measure of fit improves, so the analysis keeps the continuous score.</li>
</ul>
<aside class="notes">
<p>For questions about whether the continuous score is the right framing.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><i class="fa-brands fa-github"></i> <a href="https://github.com/amirhosseinghdv">amirhosseinghdv</a> <i class="fa-brands fa-linkedin"></i> <a href="https://www.linkedin.com/in/amirhossein-ghadiri-8296781a6/">amirhossein-ghadiri</a> 🌐 <a href="https://amirhosseinghdv.github.io/">amirhosseinghdv.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":false},
'chalkboard': {"buttons":true,"theme":"chalkboard","toggleNotesButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/amirhosseinghdv\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>